-- Seed batch 2: startup-product (12), ui-ux (12), indian-business (12), data-analytics (12)

-- ============================================================
-- CATEGORY: startup-product (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'mvp-scope-definer','MVP Scope Definer','Define a shippable MVP in 1 hour from a product idea','Turn any product idea into a scoped, shippable MVP with must-have features, user stories, and a week-by-week build plan in under one hour.',
'startup-product',NULL,ARRAY['mvp','product','startup'],'beginner',
0,0,true,
'[{"number":1,"title":"Input your idea","description":"Provide your product idea, target user, launch timeline, and budget as structured input.","code":"const input = {\n  idea: \"AI-powered inventory for Indian kirana stores\",\n  targetUser: \"shop owner\",\n  timeToLaunch: \"3 months\",\n  budget: \"₹5L\"\n};","language":"typescript"},{"number":2,"title":"Get must-have vs nice-to-have split","description":"Output shows core features that validate the hypothesis vs features that can wait for later iterations."},{"number":3,"title":"Generate user story list","description":"Get a full set of user stories scoped to the MVP.","code":"[\n  \"As a shop owner, I can scan a product barcode to add to inventory\",\n  \"As a shop owner, I get WhatsApp alerts when stock is low\"\n]","language":"typescript"},{"number":4,"title":"Create week-by-week build plan","description":"Generate a build plan with specific deliverables per week tied to your launch timeline."}]'::jsonb,
NULL,NULL,920,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'pitch-deck-outliner','Pitch Deck Outliner','Structure a 10-slide investor pitch deck from your startup description','Generate a structured 10-slide investor pitch deck outline from any startup description, with slide-by-slide content, talking points, and three format variants.',
'startup-product',NULL,ARRAY['pitch-deck','fundraising','startup'],'beginner',
0,0,true,
'[{"number":1,"title":"Input company description","description":"Provide your company description and request the 10 standard slides: Problem, Solution, Market, Product, Traction, Business Model, Competition, Team, Financials, Ask."},{"number":2,"title":"Get content outline per slide","description":"Receive a detailed content outline for each slide with key metrics and talking points specific to your startup."},{"number":3,"title":"Generate speaker notes","description":"Get speaker notes for every slide to help you present confidently with supporting detail."},{"number":4,"title":"Create three format variants","description":"Receive three tailored versions of the deck: seed round, Series A, and demo day formats with adjusted emphasis and metrics."}]'::jsonb,
NULL,NULL,880,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'prd-writer','PRD Writer','Generate a complete Product Requirements Document from a feature brief','Generate a complete, structured Product Requirements Document from a brief feature description — covering goals, user stories, functional requirements, and success metrics.',
'startup-product',NULL,ARRAY['prd','product','documentation'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input feature brief","description":"Provide the feature brief including the user problem being solved and the desired goals for this feature."},{"number":2,"title":"Get full PRD structure","description":"Receive the complete PRD: Overview, Goals, Non-goals, User Stories, Functional Requirements, Non-functional Requirements, and Success Metrics."},{"number":3,"title":"Generate acceptance criteria","description":"Get specific, testable acceptance criteria for every functional requirement in the PRD."},{"number":4,"title":"Export to Notion or Confluence","description":"Export the PRD as Notion or Confluence-compatible markdown ready to paste into your workspace."}]'::jsonb,
NULL,NULL,750,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'competitive-analysis-matrix','Competitive Analysis Matrix','Map your product against 5 competitors across 20 dimensions','Build a comprehensive competitive analysis matrix comparing your product against five competitors across pricing, features, market, tech stack, and distribution dimensions.',
'startup-product',NULL,ARRAY['competitive-analysis','market-research','product'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input your product and competitors","description":"Provide your product description and list up to five competitors you want to benchmark against."},{"number":2,"title":"Define comparison dimensions","description":"Work across 20 dimensions including pricing model, feature depth, target market segment, tech stack, and distribution channels."},{"number":3,"title":"Generate filled matrix","description":"Receive a complete matrix with ratings and supporting notes for every cell, ready to drop into a spreadsheet."},{"number":4,"title":"Identify unique positioning","description":"Get a positioning analysis that identifies the whitespace gaps your product can own based on the matrix findings."}]'::jsonb,
NULL,NULL,700,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'user-persona-creator','User Persona Creator','Build data-driven ICP profiles and buyer personas for any product','Generate three detailed, data-driven user personas for any product — primary ICP, secondary user, and decision maker — with demographics, goals, frustrations, and buying triggers.',
'startup-product',NULL,ARRAY['persona','ux','marketing'],'beginner',
0,0,true,
'[{"number":1,"title":"Input product and target market","description":"Describe your product and the target market you are trying to reach with sufficient detail for realistic persona generation."},{"number":2,"title":"Generate three personas","description":"Receive three personas: primary ICP (ideal customer), secondary user, and decision maker or economic buyer."},{"number":3,"title":"Get full persona attributes","description":"Each persona includes demographics, primary goals, key frustrations, buying triggers, and preferred communication channels."},{"number":4,"title":"Export persona cards","description":"Get a one-page persona card in markdown for each persona, ready to share with your team or paste into a PRD."}]'::jsonb,
NULL,NULL,680,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'go-to-market-planner','GTM Planner','Build a 90-day go-to-market plan with channels, messaging and KPIs','Build a complete 90-day go-to-market plan including channel prioritization by CAC efficiency, messaging framework, and a week-by-week execution calendar with KPIs.',
'startup-product',NULL,ARRAY['gtm','marketing','growth'],'intermediate',
199900,1900,false,
'[{"number":1,"title":"Input product, ICP, budget, and launch date","description":"Provide your product description, ideal customer profile, available marketing budget, and target launch date."},{"number":2,"title":"Get channel recommendations","description":"Receive a ranked list of go-to-market channels ordered by estimated CAC efficiency for your specific ICP and budget."},{"number":3,"title":"Generate messaging framework","description":"Get your complete messaging framework: hero headline, value propositions, proof points, and objection handling."},{"number":4,"title":"Week-by-week execution plan","description":"Receive a week-by-week 90-day execution plan with specific tasks, KPIs, and recommended owners for each activity."}]'::jsonb,
NULL,NULL,760,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'startup-idea-validator','Startup Idea Validator','Score your startup idea on 8 dimensions before you build anything','Score any startup idea across eight critical dimensions and get a data-backed go/no-go recommendation with actionable validation experiments before you write a line of code.',
'startup-product',NULL,ARRAY['validation','startup','ideation'],'beginner',
0,0,true,
'[{"number":1,"title":"Input your idea in 2-3 sentences","description":"Describe your startup idea clearly and concisely in two to three sentences including the problem, solution, and target customer."},{"number":2,"title":"Get scored on 8 dimensions","description":"Receive scores on: problem severity, market size, competition intensity, timing, founder-market fit, monetization clarity, distribution path, and defensibility."},{"number":3,"title":"Get go/no-go recommendation","description":"Receive a clear go or no-go recommendation with the reasoning behind the score on each dimension."},{"number":4,"title":"Get validation experiments","description":"Receive three specific validation experiments you can run in the next two weeks to test your riskiest assumptions cheaply."}]'::jsonb,
NULL,NULL,870,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'product-roadmap-builder','Product Roadmap Builder','Generate a prioritized quarterly roadmap from goals and user feedback','Turn business goals, user feedback themes, and tech debt into a RICE-prioritized quarterly product roadmap with a Now/Next/Later structure exportable to Linear or Notion.',
'startup-product',NULL,ARRAY['roadmap','product','planning'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input goals, feedback, and tech debt","description":"Provide your business goals for the quarter, top user feedback themes, and known tech debt items that need addressing."},{"number":2,"title":"RICE scoring for all items","description":"Every feature and initiative is scored using the RICE framework: Reach times Impact times Confidence divided by Effort."},{"number":3,"title":"Generate Now/Next/Later roadmap","description":"Receive a themed roadmap with items organized into Now (this quarter), Next (next quarter), and Later (backlog) buckets."},{"number":4,"title":"Export for Linear or Notion","description":"Get your roadmap as a markdown table or JSON payload ready to import into Linear, Notion, or your planning tool of choice."}]'::jsonb,
NULL,NULL,720,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'unit-economics-calculator','Unit Economics Calculator','Calculate CAC, LTV, payback period and set targets automatically','Calculate your key SaaS unit economics — CAC, LTV, payback period, and LTV:CAC ratio — then benchmark against industry standards and get specific improvement recommendations.',
'startup-product',NULL,ARRAY['unit-economics','finance','saas'],'intermediate',
0,0,true,
'[{"number":1,"title":"Input your financial inputs","description":"Provide: MRR, monthly churn rate, average contract value, total sales and marketing spend, and new customers acquired per month."},{"number":2,"title":"Calculate core metrics","description":"Get: CAC equals total sales spend divided by new customers, LTV equals ARPU divided by churn rate, and LTV to CAC ratio calculated automatically."},{"number":3,"title":"Benchmark against SaaS standards","description":"Your metrics are compared to SaaS benchmarks: LTV to CAC ratio above 3x is healthy, payback period under 18 months is target."},{"number":4,"title":"Get improvement recommendations","description":"Receive specific, prioritized recommendations to improve each metric based on where you are versus the benchmark."}]'::jsonb,
NULL,NULL,800,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'job-description-writer','JD Writer','Write bias-free, high-converting job descriptions for technical roles','Write bias-free, high-converting job descriptions for any technical role with built-in gender-coded language checks and three platform-specific variants.',
'startup-product',NULL,ARRAY['hiring','hr','recruiting'],'beginner',
0,0,true,
'[{"number":1,"title":"Input role details","description":"Provide: role title, team context, key responsibilities, must-have requirements, nice-to-haves, and salary or equity range."},{"number":2,"title":"Get structured job description","description":"Receive a fully structured JD with sections: About Us, The Role, What You Will Do, Requirements, Nice to Have, and What We Offer."},{"number":3,"title":"Bias check applied","description":"The output is checked for and stripped of gender-coded language, age-related requirements, and unnecessary degree requirements that reduce application volume."},{"number":4,"title":"Three platform variants","description":"Get three variations of the JD optimized for different job boards such as LinkedIn, AngelList, and company careers page."}]'::jsonb,
NULL,NULL,650,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'landing-page-copywriter','Landing Page Copywriter','Write high-converting landing page copy: hero, features, CTA, FAQs','Generate complete, high-converting landing page copy — hero headline, subheadline, feature bullets, FAQs, and CTA variants — from a single product brief.',
'startup-product',NULL,ARRAY['copywriting','landing-page','marketing'],'beginner',
0,0,true,
'[{"number":1,"title":"Input product brief","description":"Provide: product name, the core ICP pain point being solved, the single biggest benefit, and any social proof currently available."},{"number":2,"title":"Get headline and subheadline variants","description":"Receive multiple headline variants — problem-focused, benefit-focused, and curiosity-driven — plus matching subheadlines for each."},{"number":3,"title":"Generate FAQ from objections","description":"Get a full FAQ section built from the most common objections your target customer would have before buying."},{"number":4,"title":"Write CTA variants","description":"Get three CTA button copy variations with an A/B test recommendation for which to run first and which to test second."}]'::jsonb,
NULL,NULL,910,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'investor-update-writer','Investor Update Writer','Write compelling monthly investor updates in 10 minutes','Write transparent, confident monthly investor updates in under 10 minutes by inputting your key metrics and letting the skill structure the narrative and subject lines.',
'startup-product',NULL,ARRAY['fundraising','investor-relations','startup'],'beginner',
0,0,true,
'[{"number":1,"title":"Input your monthly metrics","description":"Provide: current MRR, month-over-month growth rate, top three wins, top two challenges, and any specific asks for your investors."},{"number":2,"title":"Get structured update","description":"Receive the standard investor update format: MRR chart narrative, highlights, lowlights, metrics table, and help needed section."},{"number":3,"title":"Tone calibration","description":"The update is written in a tone that is transparent and honest about challenges while remaining confident about the path forward."},{"number":4,"title":"Subject line variants","description":"Get three subject line options for the email ranging from metrics-forward to narrative-forward styles."}]'::jsonb,
NULL,NULL,620,0,0,false,true,false,NULL,true);

-- ============================================================
-- CATEGORY: ui-ux (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'wireframe-describer','Wireframe Describer','Turn a product description into detailed wireframe specs for any screen','Convert any product description into detailed wireframe specifications including layout grids, component lists, interaction specs, and responsive breakpoints.',
'ui-ux',NULL,ARRAY['wireframe','ux','design'],'beginner',
0,0,true,
'[{"number":1,"title":"Input screen details","description":"Provide: the screen name, the user goal this screen serves, and the data available to be displayed."},{"number":2,"title":"Get layout and component spec","description":"Receive a layout grid description and a complete component list with position and sizing for every element on the screen."},{"number":3,"title":"Interaction specification","description":"Get a detailed interaction spec describing exactly what happens for each possible user action on the screen."},{"number":4,"title":"Responsive breakpoints","description":"Receive mobile-first layout adjustments with specific changes at tablet and desktop breakpoints."}]'::jsonb,
NULL,NULL,780,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'design-system-builder','Design System Builder','Generate design tokens, component specs and Tailwind config from a brand','Generate a complete design system from brand inputs — color scales, typography, spacing, a full Tailwind config, and component specs for core UI elements.',
'ui-ux',NULL,ARRAY['design-system','tailwind','tokens'],'intermediate',
199900,1900,false,
'[{"number":1,"title":"Input brand identity","description":"Provide: primary brand color hex, secondary color hex, accent color hex, preferred font family, and three adjectives describing brand personality."},{"number":2,"title":"Get complete token scales","description":"Receive a full 50 through 950 color scale for each brand color, a typography scale with sizes and line heights, and a spacing scale."},{"number":3,"title":"Generate tailwind.config.ts","description":"Get a complete tailwind.config.ts file with all design tokens wired up and ready to drop into any Next.js project."},{"number":4,"title":"Core component specs","description":"Receive component specifications for Button, Input, Card, Badge, and Modal with all variants and states fully defined."}]'::jsonb,
NULL,NULL,820,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'user-flow-mapper','User Flow Mapper','Map every user journey from entry point to conversion as a flow diagram spec','Map complete user journeys from every entry point to conversion — including decision points, edge cases, error states, and Mermaid diagram code for each flow.',
'ui-ux',NULL,ARRAY['user-flow','ux','product'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input feature and entry points","description":"Provide: the feature being mapped, the user type completing the journey, and all possible entry points to this flow."},{"number":2,"title":"Get step-by-step flow with decision points","description":"Receive a complete flow with every step, decision branch, and the happy path clearly marked."},{"number":3,"title":"Edge cases and error states","description":"Get a comprehensive list of edge cases and error states mapped to the correct point in the flow where they occur."},{"number":4,"title":"Mermaid diagram code","description":"Receive ready-to-render Mermaid diagram code for each flow. Example: graph TD; A[Landing] --> B{Signed in?} --> C[Dashboard] or D[Sign up]"}]'::jsonb,
NULL,NULL,680,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'react-component-specifier','React Component Specifier','Generate typed React component specs with props, states and variants','Generate complete TypeScript React component specifications including typed prop interfaces, state management patterns, Storybook stories, and accessibility requirements.',
'ui-ux',NULL,ARRAY['react','typescript','components'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Describe the component","description":"Describe the component purpose, where it will be used in the product, and what data it needs to receive and display."},{"number":2,"title":"Get TypeScript interface and state pattern","description":"Receive a typed TypeScript interface for all props, the recommended state management pattern, and a full list of supported variants."},{"number":3,"title":"Generate Storybook story file","description":"Get a complete Storybook story file with stories for every variant and interactive controls for all configurable props."},{"number":4,"title":"Accessibility requirements","description":"Receive the full accessibility spec: required ARIA roles, keyboard navigation behavior, and screen reader label requirements."}]'::jsonb,
NULL,NULL,700,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'accessibility-auditor','Accessibility Auditor','WCAG 2.1 AA compliance check with specific fixes for React components','Audit any React component JSX against WCAG 2.1 AA standards and receive a prioritized list of issues with specific code fixes and automated testing commands.',
'ui-ux',NULL,ARRAY['accessibility','wcag','react'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Paste component JSX","description":"Paste the React component JSX you want audited for WCAG 2.1 AA compliance issues."},{"number":2,"title":"Get issues list","description":"Receive all identified issues including: missing aria-labels, low contrast ratios, absent keyboard navigation, and improper heading hierarchy."},{"number":3,"title":"Get specific code fixes","description":"Every issue comes with a specific, copy-paste ready code fix rather than generic guidance."},{"number":4,"title":"Run automated checks","description":"Get the automated testing command to run against your local build: npx axe-core-cli http://localhost:3000","code":"npx axe-core-cli http://localhost:3000","language":"bash"}]'::jsonb,
NULL,NULL,640,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'mobile-app-ui-designer','Mobile App UI Designer','Get detailed mobile screen specs: layout, interactions, gestures','Generate detailed mobile screen specifications including layout, content areas, gesture interactions, and platform-specific differences between iOS and Android.',
'ui-ux',NULL,ARRAY['mobile','react-native','ui'],'intermediate',
199900,1900,false,
'[{"number":1,"title":"Describe the screen","description":"Provide: the screen purpose, the data to be displayed, and the user actions available on this screen."},{"number":2,"title":"Get layout specification","description":"Receive the complete layout spec: header structure, content area breakdown, and bottom navigation or tab bar configuration."},{"number":3,"title":"Interaction specification","description":"Get full interaction specs for swipe actions, pull-to-refresh behavior, and infinite scroll implementation details."},{"number":4,"title":"Platform differences","description":"Receive a side-by-side breakdown of iOS versus Android conventions for this specific screen type so you build it right for both platforms."}]'::jsonb,
NULL,NULL,760,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'dashboard-layout-planner','Dashboard Layout Planner','Design analytics dashboards: KPI cards, charts, tables and filters','Design complete analytics dashboards with grid layout specs, widget sizing, chart type recommendations per metric, and a filter panel specification.',
'ui-ux',NULL,ARRAY['dashboard','analytics','ui'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input metrics, user role, and refresh frequency","description":"Provide: the list of metrics to display, the user role viewing the dashboard, and how frequently the data refreshes."},{"number":2,"title":"Get grid layout spec with widget sizes","description":"Receive a grid layout specification with precise widget sizes and positions optimized for the metrics and screen real estate."},{"number":3,"title":"Chart type recommendations","description":"Get the recommended chart type for each metric based on data type, comparison need, and time dimension."},{"number":4,"title":"Filter panel specification","description":"Receive a complete filter panel spec including date range picker, dimension filters, and search configuration."}]'::jsonb,
NULL,NULL,720,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'onboarding-flow-designer','Onboarding Flow Designer','Design user onboarding: steps, progress, empty states and activation','Design a complete user onboarding flow ordered by friction, with empty state designs, progress tracking recommendations, and activation milestone celebrations.',
'ui-ux',NULL,ARRAY['onboarding','ux','saas'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input product, activation metric, and user type","description":"Provide: the product being onboarded, the single activation metric that defines a successful new user, and the user type going through onboarding."},{"number":2,"title":"Get onboarding steps ordered by friction","description":"Receive the recommended onboarding steps ordered from lowest to highest friction to maximize completion rates."},{"number":3,"title":"Empty state designs","description":"Get empty state copy and visual direction for every key screen the new user will encounter before they have data."},{"number":4,"title":"Progress tracking recommendation","description":"Receive a recommendation for checklist versus progress bar with the specific trigger point for showing a celebration or success state."}]'::jsonb,
NULL,NULL,700,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'color-palette-generator','Color Palette Generator','Generate accessible brand color systems with dark mode variants','Generate a complete accessible brand color system — full 50-950 scale, semantic colors, dark mode equivalents, and contrast ratio verification for all text and background combinations.',
'ui-ux',NULL,ARRAY['colors','design','branding'],'beginner',
0,0,true,
'[{"number":1,"title":"Input primary brand color and personality","description":"Provide your primary brand color hex code and three words describing your brand personality such as professional, playful, or bold."},{"number":2,"title":"Get full color scale and semantic colors","description":"Receive a complete 50 through 950 scale for your primary color plus semantic colors for success, warning, error, and info states."},{"number":3,"title":"Dark mode equivalents","description":"Get dark mode color equivalents for every color in the system ensuring visual consistency across both themes."},{"number":4,"title":"Contrast ratio verification","description":"Every text and background color combination is checked against WCAG contrast requirements. Formula: const ratio = (l1 + 0.05) / (l2 + 0.05)","code":"const ratio = (l1 + 0.05) / (l2 + 0.05);","language":"typescript"}]'::jsonb,
NULL,NULL,750,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'micro-interaction-specifier','Micro-Interaction Specifier','Specify animations and transitions that make UIs feel polished and fast','Specify every animation and transition your UI needs — timing, easing, delay — with CSS and Framer Motion code and performance guidelines to avoid layout thrash.',
'ui-ux',NULL,ARRAY['animation','css','ux'],'intermediate',
99900,900,false,
'[{"number":1,"title":"List UI actions needing feedback","description":"List the UI actions that need motion feedback such as button click, form submission, page navigation, and toast notifications."},{"number":2,"title":"Get timing and easing specs","description":"Receive precise timing specifications: duration in milliseconds, easing curve, and delay for each interaction."},{"number":3,"title":"CSS and Framer Motion code","description":"Get ready-to-use CSS transitions or Framer Motion animation code for every interaction specified."},{"number":4,"title":"Performance guidelines","description":"Receive performance rules for each animation: use transform and opacity only, avoid properties that trigger layout recalculation."}]'::jsonb,
NULL,NULL,620,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'design-critique-reviewer','Design Critique Reviewer','Get structured design feedback on UI screenshots using UX principles','Get structured, principled design critique on any UI — covering visual hierarchy, whitespace, consistency, contrast, and information architecture with prioritized fixes.',
'ui-ux',NULL,ARRAY['design-review','ux','feedback'],'beginner',
0,0,true,
'[{"number":1,"title":"Describe or provide screenshot context","description":"Describe the UI screen or provide a screenshot with context about the user goal and the product type."},{"number":2,"title":"Get structured critique","description":"Receive critique across five UX dimensions: visual hierarchy, whitespace usage, consistency, contrast ratios, and information architecture."},{"number":3,"title":"Prioritized fix list","description":"All issues are classified as critical blockers versus nice-to-have improvements so you know where to focus your time."},{"number":4,"title":"Before and after description","description":"Receive a before and after description of the improved layout for each critical issue to guide your redesign."}]'::jsonb,
NULL,NULL,660,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'component-naming-guide','Component Naming Guide','Generate consistent, scalable naming conventions for design systems','Standardize your design system component naming with consistent PascalCase conventions, folder structure recommendations, and Storybook category mapping.',
'ui-ux',NULL,ARRAY['naming','design-system','components'],'beginner',
0,0,true,
'[{"number":1,"title":"Input existing component names","description":"Paste your current messy list of component names so the skill can analyze the inconsistencies and suggest a systematic fix."},{"number":2,"title":"Get standardized naming convention","description":"Receive a consistent naming convention using PascalCase and prefix patterns that scales as your component library grows."},{"number":3,"title":"Folder structure recommendation","description":"Get a recommended folder and file structure for your design system that makes components discoverable and maintainable."},{"number":4,"title":"Storybook category mapping","description":"Receive a Storybook category and subcategory mapping for every component so your docs are organized consistently."}]'::jsonb,
NULL,NULL,560,0,0,false,true,false,NULL,true);

-- ============================================================
-- CATEGORY: indian-business (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'gst-invoice-generator','GST Invoice Generator','Generate GST-compliant invoices with CGST/SGST/IGST calculations','Generate fully GST-compliant invoices with automatic CGST/SGST for intra-state and IGST for inter-state transactions, including all mandatory fields and format validation.',
'indian-business',NULL,ARRAY['gst','invoice','india'],'beginner',
0,0,true,
'[{"number":1,"title":"Input seller, buyer, and line items","description":"Provide seller GSTIN and details, buyer details and state, and line items with HSN codes, quantities, unit prices, and applicable GST rates."},{"number":2,"title":"Auto-calculate tax breakdown","description":"The skill automatically applies CGST plus SGST for intra-state transactions and IGST for inter-state transactions with correct split percentages."},{"number":3,"title":"Generate invoice in HTML or PDF format","description":"Receive the invoice in HTML or PDF format with all mandatory GST fields: GSTIN, HSN, tax amounts, IRN placeholder, and QR code placeholder."},{"number":4,"title":"Validate against GST format requirements","description":"Get a mandatory fields checklist verified against GST invoice format requirements so you can be confident the invoice is compliant."}]'::jsonb,
NULL,NULL,950,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'gst-tax-calculator','GST Tax Calculator','Calculate CGST, SGST, IGST, cess for any transaction type','Calculate the precise GST breakdown for any Indian transaction — CGST, SGST, IGST, and applicable cess — including reverse calculation from GST-inclusive prices.',
'indian-business',NULL,ARRAY['gst','tax','india'],'beginner',
0,0,true,
'[{"number":1,"title":"Input transaction details","description":"Provide: transaction value, supply type (intra-state or inter-state), and the applicable GST rate (5%, 12%, 18%, or 28%)."},{"number":2,"title":"Get complete tax breakdown","description":"Receive: taxable value, CGST percentage and amount, SGST percentage and amount or IGST percentage and amount, plus cess if applicable."},{"number":3,"title":"Reverse calculation","description":"Input a GST-inclusive price to get the pre-GST base amount and each tax component calculated backwards."},{"number":4,"title":"Composition scheme rates","description":"Get the special GST rates applicable for businesses registered under the Composition Scheme for eligible sectors."}]'::jsonb,
NULL,NULL,900,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'tds-calculator','TDS Calculator','Calculate TDS on salary, contractor payments, rent and professional fees','Calculate the correct TDS deduction for any payment type — salary, contractor, rent, or professional fees — with the applicable section, rate, threshold, and Form 16A data.',
'indian-business',NULL,ARRAY['tds','income-tax','india'],'intermediate',
0,0,true,
'[{"number":1,"title":"Input payment type and amount","description":"Provide the payment type (salary, contractor payment, rent, or professional fees) and the gross payment amount."},{"number":2,"title":"Get applicable section, rate, and threshold","description":"Receive the applicable TDS section (such as 194C for contractors, 194J for professional fees, 194I for rent), the TDS rate, and the threshold limit."},{"number":3,"title":"Calculate net payment after TDS","description":"Get the TDS amount to be deducted and the net amount payable to the recipient after deduction."},{"number":4,"title":"Generate Form 16A data","description":"Receive the data fields required for Form 16A generation for quarterly TDS return filing."}]'::jsonb,
NULL,NULL,820,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'gst-return-guide','GST Return Guide','Step-by-step GSTR-1, GSTR-3B and GSTR-9 filing guide with deadlines','A complete step-by-step guide to filing GSTR-1, GSTR-3B, and annual GSTR-9 returns with exact due dates, ITC reconciliation instructions, and common error fixes.',
'indian-business',NULL,ARRAY['gst','returns','compliance'],'intermediate',
0,0,true,
'[{"number":1,"title":"GSTR-1: Outward supply filing","description":"GSTR-1 covers outward supply details. File by the 11th of the following month for monthly filers. Report all B2B invoices, B2C summaries, credit notes, and amendments."},{"number":2,"title":"GSTR-3B: Monthly summary payment","description":"GSTR-3B is the monthly summary return. Populate from your GSTR-1 data, claim eligible ITC, and pay net tax liability by the 20th of the following month."},{"number":3,"title":"GSTR-2B reconciliation","description":"Match your Input Tax Credit claims against GSTR-2B auto-generated from supplier filings. Flag mismatches before filing 3B to avoid ITC reversal."},{"number":4,"title":"Annual GSTR-9 reconciliation","description":"GSTR-9 is the annual return due by 31st December. Reconcile the entire year across all monthly returns and declare any adjustments or pending liabilities."}]'::jsonb,
NULL,NULL,870,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'payroll-calculator-india','Indian Payroll Calculator','Calculate take-home pay with PF, ESI, PT and income tax deductions','Calculate accurate take-home pay for any Indian employee including PF, ESI, Professional Tax, and income tax under both old and new regimes with a monthly payslip template.',
'indian-business',NULL,ARRAY['payroll','hr','india'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input CTC and components","description":"Provide: CTC amount, salary components (basic, HRA, special allowance), and city tier (metro or non-metro) for HRA exemption calculation."},{"number":2,"title":"Calculate statutory deductions","description":"PF is 12 percent of basic salary with employer capped at ₹1800 per month. ESI applies at 3.25 percent employer and 0.75 percent employee for salaries below ₹21,000."},{"number":3,"title":"Income tax comparison","description":"Get a side-by-side comparison of tax liability under the new regime versus the old regime with deductions so the employee can choose optimally."},{"number":4,"title":"Generate monthly payslip template","description":"Receive a formatted monthly payslip template with all earnings, deductions, and net take-home pay clearly laid out."}]'::jsonb,
NULL,NULL,780,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'export-invoice-generator','Export Invoice Generator','Create export invoices with LUT/IGST option, FIRC tracking','Generate compliant export invoices for Indian exporters with zero-rated LUT or IGST-paid options, RBI exchange rate conversion, and all mandatory export fields.',
'indian-business',NULL,ARRAY['export','gst','invoice'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input exporter and buyer details","description":"Provide: exporter GSTIN, foreign buyer details, invoice amount in USD or EUR, and shipping terms (CIF, FOB, etc)."},{"number":2,"title":"Choose LUT or IGST option","description":"Select between zero-rated supply under Letter of Undertaking with no IGST, or supply with IGST charged for claiming a refund."},{"number":3,"title":"Generate compliant export invoice","description":"Receive the invoice with: foreign currency amount, INR equivalent at RBI reference rate, FIRC number field, and all mandatory export fields."},{"number":4,"title":"Mandatory export fields checklist","description":"Get confirmation of all mandatory fields: AD code, port of loading, country of destination, shipping bill number placeholder, and LUT or bond number."}]'::jsonb,
NULL,NULL,650,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'msme-compliance-guide','MSME Compliance Guide','Udyam registration, MSME benefits, and payment protection rules','Complete guide to MSME Udyam registration eligibility, step-by-step registration process, available benefits, and payment protection rights under the MSMED Act 2006.',
'indian-business',NULL,ARRAY['msme','compliance','india'],'beginner',
0,0,true,
'[{"number":1,"title":"Check eligibility","description":"Verify eligibility based on enterprise type (manufacturing or service), annual turnover limit, and plant and machinery or equipment investment limit."},{"number":2,"title":"Udyam registration process","description":"Step-by-step registration at udyamregistration.gov.in using Aadhaar and PAN — no documents need to be uploaded, it is fully self-declaration based."},{"number":3,"title":"MSME benefits overview","description":"Key benefits include: priority sector lending, 1 percent interest subsidy under CGTMSE, GeM portal registration preference, and fast-track patent and trademark filing."},{"number":4,"title":"Payment protection rights","description":"Under MSMED Act 2006, buyers must pay MSME suppliers within 45 days. Delayed payment attracts compound interest at three times the RBI bank rate."}]'::jsonb,
NULL,NULL,700,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'itr-filing-guide-business','Business ITR Filing Guide','ITR-3 and ITR-4 filing guide for business owners and freelancers','A complete guide to selecting and filing the correct ITR form for business owners and freelancers — ITR-3 or ITR-4 — with deduction checklists and advance tax schedules.',
'indian-business',NULL,ARRAY['income-tax','itr','india'],'intermediate',
0,0,true,
'[{"number":1,"title":"Choose the correct ITR form","description":"ITR-4 is for presumptive income under sections 44AD and 44ADA. ITR-3 is for businesses maintaining regular books of accounts. Get the right form for your situation."},{"number":2,"title":"Presumptive taxation under 44AD","description":"Under section 44AD, declare 6 percent of digital turnover or 8 percent of cash turnover as net profit without maintaining detailed books."},{"number":3,"title":"Deductions checklist","description":"Complete checklist of available deductions: 80C investments, 80D health insurance, HRA exemption, home loan interest under Section 24, and business expenses."},{"number":4,"title":"Advance tax payment schedule","description":"Advance tax deadlines: 15 percent by June 15, 45 percent by September 15, 75 percent by December 15, and 100 percent by March 15."}]'::jsonb,
NULL,NULL,840,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'vendor-agreement-drafter','Vendor Agreement Drafter','Generate standard vendor contracts with payment terms, IP clauses, SLA','Generate India-compliant vendor agreements with scope, payment terms, IP ownership, confidentiality, TDS and GST clauses, and milestone-based payment protection.',
'indian-business',NULL,ARRAY['legal','contracts','business'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input parties, scope, and payment terms","description":"Provide: both party names and addresses, the scope of work, payment terms, key deliverables, and the desired governing jurisdiction."},{"number":2,"title":"Get standard contract clauses","description":"Receive all standard clauses: scope of work, payment schedule, intellectual property ownership, confidentiality obligations, and termination conditions."},{"number":3,"title":"India-specific legal clauses","description":"Get India-specific clauses: GST applicability and invoice requirements, TDS deduction obligation, and choice of jurisdiction city for dispute resolution."},{"number":4,"title":"Payment protection structure","description":"Receive recommendations for milestone-linked payment structure, advance percentage, and retention amount to protect both parties throughout the engagement."}]'::jsonb,
NULL,NULL,620,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'startup-india-registration','Startup India Registration','DPIIT recognition step-by-step: eligibility, documents, and benefits','Complete step-by-step guide to obtaining DPIIT recognition under Startup India — eligibility criteria, required documents, registration process, and all available benefits.',
'indian-business',NULL,ARRAY['startup-india','dpiit','compliance'],'beginner',
0,0,true,
'[{"number":1,"title":"Check DPIIT eligibility","description":"Your startup must be incorporated for less than 10 years, have turnover below ₹100 crore in any financial year, and work on an innovative product, service, or scalable business model."},{"number":2,"title":"Registration process on startupindia.gov.in","description":"Register at startupindia.gov.in and upload: certificate of incorporation, PAN, and a pitch deck or description of the innovative nature of your business."},{"number":3,"title":"Core DPIIT benefits","description":"Key benefits after recognition: Section 80IAC income tax holiday for 3 years, angel tax exemption under Section 56(2)(viib), and fast-track patent application processing."},{"number":4,"title":"Post-recognition funding access","description":"After recognition apply for the Startup India Seed Fund Scheme (up to ₹50 lakh) and access SIDBI Fund of Funds for equity funding from SEBI-registered AIFs."}]'::jsonb,
NULL,NULL,760,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'shop-act-compliance','Shop Act Compliance','Shop and Establishment Act registration for any Indian state','State-specific guide to Shop and Establishment Act registration covering eligibility, required documents, online registration process, and annual renewal obligations.',
'indian-business',NULL,ARRAY['compliance','shop-act','india'],'beginner',
0,0,true,
'[{"number":1,"title":"Check state-specific rules","description":"Each Indian state has its own Shop and Establishment Act with different rules. Identify the correct act for your state such as Maharashtra, Delhi, Karnataka, Tamil Nadu, or Gujarat."},{"number":2,"title":"Documents required","description":"Standard documents needed: business address proof, owner identity proof, lease or rental agreement, number of employees, and nature of business description."},{"number":3,"title":"Online registration process","description":"Most states now offer online registration through the state labour department portal. Get the direct portal URL and step-by-step filing instructions for your state."},{"number":4,"title":"Renewal and compliance","description":"Annual renewal is required in most states. Understand the renewal timeline, penalty for non-compliance, and display requirements for the registration certificate."}]'::jsonb,
NULL,NULL,580,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'business-email-drafter','Business Email Drafter','Draft professional emails for payments, proposals, complaints, follow-ups','Draft professional, high-impact business emails for any scenario — payment reminders, proposals, complaints, and follow-up sequences — with the right tone every time.',
'indian-business',NULL,ARRAY['email','communication','business'],'beginner',
0,0,true,
'[{"number":1,"title":"Input email type and context","description":"Provide: the email type (payment reminder, proposal, complaint, or follow-up), recipient context, your specific ask, and the desired tone (formal, assertive, or polite)."},{"number":2,"title":"Get subject line and email body","description":"Receive a complete email with an optimized subject line and a structured body that gets to the point and drives the desired action."},{"number":3,"title":"Payment reminder template","description":"Get a payment reminder template that references the invoice amount, due date, and includes a payment link or bank details."},{"number":4,"title":"Follow-up sequence","description":"Receive a three-email follow-up sequence: Day 1 polite reminder, Day 7 firm follow-up, and Day 14 escalation email for non-responsive recipients."}]'::jsonb,
NULL,NULL,720,0,0,false,true,false,NULL,true);

-- ============================================================
-- CATEGORY: data-analytics (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'eda-pipeline-builder','EDA Pipeline Builder','Automated exploratory data analysis with Python: stats, plots, missing data','Build a complete automated EDA pipeline in Python covering dataset inspection, missing data visualization, distribution plots, correlation analysis, and outlier detection.',
'data-analytics',NULL,ARRAY['python','pandas','eda'],'intermediate',
0,0,true,
'[{"number":1,"title":"Load and inspect dataset","description":"Load your CSV and run initial inspection to understand shape, dtypes, and summary statistics.","code":"df = pd.read_csv(''data.csv'')\nprint(df.info())\nprint(df.describe())","language":"python"},{"number":2,"title":"Visualize missing data","description":"Generate a heatmap of missing values and a sorted count of nulls per column to prioritize imputation or dropping.","code":"sns.heatmap(df.isnull(), cbar=False)\ndf.isnull().sum().sort_values(ascending=False)","language":"python"},{"number":3,"title":"Distribution and correlation plots","description":"Plot histograms for all numeric columns and a horizontal bar chart of correlations with the target variable.","code":"df.hist(figsize=(15, 10))\ndf.select_dtypes(''number'').corrwith(df[''target'']).sort_values().plot.barh()","language":"python"},{"number":4,"title":"Outlier detection with IQR","description":"Identify outlier rows using the interquartile range method across all numeric columns.","code":"Q1 = df.quantile(0.25)\nQ3 = df.quantile(0.75)\nIQR = Q3 - Q1\noutliers = df[((df < Q1 - 1.5 * IQR) | (df > Q3 + 1.5 * IQR)).any(axis=1)]","language":"python"}]'::jsonb,
NULL,NULL,780,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ab-test-analyzer','A/B Test Analyzer','Statistical significance calculator: p-value, effect size, sample size','Calculate statistical significance for any A/B test — z-score, p-value, confidence interval, effect size, and minimum detectable effect — with a clear go/no-go decision.',
'data-analytics',NULL,ARRAY['ab-testing','statistics','analytics'],'intermediate',
0,0,true,
'[{"number":1,"title":"Input conversion rates and sample sizes","description":"Provide: control group conversion rate, variant group conversion rate, and sample size for each group."},{"number":2,"title":"Calculate z-score and p-value","description":"Receive the z-score, two-tailed p-value, and 95 percent confidence interval for the difference in conversion rates."},{"number":3,"title":"Check statistical significance","description":"A p-value below 0.05 indicates the result is statistically significant. Receive a clear significant or not significant verdict with interpretation."},{"number":4,"title":"Effect size and MDE","description":"Get the effect size and the minimum detectable effect for your sample sizes to understand what lift you can reliably detect.","code":"const mde = 1.96 * Math.sqrt(p * (1 - p) * (1 / n1 + 1 / n2));","language":"typescript"}]'::jsonb,
NULL,NULL,820,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'cohort-analysis-builder','Cohort Analysis Builder','Build retention cohort tables in SQL for any event-based product','Build week-over-week retention cohort tables in SQL for any event-based product — from cohort definition through activity joins to week-0 through week-12 retention output.',
'data-analytics',NULL,ARRAY['cohort','retention','sql'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Define cohorts by signup week","description":"Group users into cohorts based on their signup week or month so each cohort represents a homogeneous group of users who started at the same time."},{"number":2,"title":"Core cohort SQL with CTEs","description":"Build the foundational SQL using CTEs for cohort assignment and activity tracking across weeks.","code":"WITH cohorts AS (\n  SELECT user_id, date_trunc(''week'', created_at) AS cohort_week\n  FROM users\n),\nactivity AS (\n  SELECT user_id, date_trunc(''week'', event_at) AS activity_week\n  FROM events\n)","language":"sql"},{"number":3,"title":"Calculate weeks since signup and retention rate","description":"Join cohorts with activity, calculate weeks elapsed since the cohort week, and compute the retention percentage for each week bucket per cohort."},{"number":4,"title":"Output cohort retention table","description":"Receive a formatted cohort table showing week-0 through week-12 retention percentages for each cohort, ready to paste into a spreadsheet or BI tool."}]'::jsonb,
NULL,NULL,750,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'funnel-analysis-sql','Funnel Analysis SQL','Build multi-step conversion funnels in PostgreSQL or BigQuery','Build multi-step conversion funnel queries in PostgreSQL or BigQuery using window functions, calculate step-by-step drop-off, and segment by acquisition channel.',
'data-analytics',NULL,ARRAY['funnel','sql','analytics'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Define funnel steps","description":"Define your funnel steps in sequence, for example: visit, signup, activate, and purchase — each mapped to a specific event name in your events table."},{"number":2,"title":"SQL with window functions","description":"Build the funnel query using conditional aggregation to flag each step completion per user.","code":"SELECT\n  user_id,\n  MAX(CASE WHEN event = ''visit'' THEN 1 END) AS step1,\n  MAX(CASE WHEN event = ''signup'' THEN 1 END) AS step2,\n  MAX(CASE WHEN event = ''activate'' THEN 1 END) AS step3,\n  MAX(CASE WHEN event = ''purchase'' THEN 1 END) AS step4\nFROM events\nGROUP BY user_id","language":"sql"},{"number":3,"title":"Calculate drop-off between steps","description":"Wrap the base query to calculate the absolute and percentage drop-off between each consecutive funnel step."},{"number":4,"title":"Segment by acquisition channel","description":"Add acquisition channel segmentation to identify which traffic sources have the highest conversion rates through your funnel."}]'::jsonb,
NULL,NULL,720,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'kpi-framework-builder','KPI Framework Builder','Build a KPI tree from business goals: north star, leading, lagging metrics','Decompose any business goal into a full KPI tree — north star metric, driver metrics, and input metrics — with definitions, data sources, owners, and targets.',
'data-analytics',NULL,ARRAY['kpi','metrics','analytics'],'intermediate',
0,0,true,
'[{"number":1,"title":"Input your business goal","description":"State your top business goal clearly, for example: grow MRR by 3x in 12 months."},{"number":2,"title":"Decompose into KPI tree","description":"Receive the full KPI tree: north star metric at the top, driver metrics in the middle, and input metrics at the bottom that teams can directly influence."},{"number":3,"title":"Define each metric fully","description":"Every metric gets a complete definition: formula, data source, measurement frequency, metric owner, and quarterly target."},{"number":4,"title":"Generate tracking template","description":"Get a Notion table or Google Sheets template with all metrics pre-populated and formula columns ready to wire to your data source."}]'::jsonb,
NULL,NULL,760,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'data-quality-checker','Data Quality Checker','Generate data validation rules and Great Expectations test suites','Generate comprehensive data quality validation rules and Great Expectations test suites plus dbt test definitions for any schema to catch data issues before they reach production.',
'data-analytics',NULL,ARRAY['data-quality','great-expectations','dbt'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Input schema and sample data","description":"Provide your table schema with column names and types plus a sample of the data so the skill can infer appropriate validation rules."},{"number":2,"title":"Generate validation rules","description":"Receive a comprehensive rule set covering: not-null constraints, uniqueness checks, value range bounds, allowed values, and referential integrity between tables."},{"number":3,"title":"Great Expectations test suite","description":"Get a complete Great Expectations expectation suite with expectations including expect_column_values_to_not_be_null, expect_column_values_to_be_between, and expect_column_pair_values_to_be_equal."},{"number":4,"title":"dbt test definitions","description":"Receive the equivalent dbt test definitions in YAML covering not_null, unique, accepted_values, and relationships tests ready to add to your dbt schema.yml."}]'::jsonb,
NULL,NULL,660,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ml-feature-engineer','ML Feature Engineer','Generate feature engineering code from raw tabular data description','Generate production-ready feature engineering code for any ML problem — numeric transforms, categorical encodings, and time-based features — from a raw data description.',
'data-analytics',NULL,ARRAY['ml','feature-engineering','python'],'advanced',
199900,1900,false,
'[{"number":1,"title":"Input raw features and prediction target","description":"Describe your raw input features, their data types, and the prediction target your model needs to learn."},{"number":2,"title":"Numeric feature transforms","description":"Get code for appropriate numeric transforms: standard scaling, min-max scaling, log transforms for skewed distributions, and value binning."},{"number":3,"title":"Categorical encoding","description":"Receive encoding strategies per column: one-hot encoding for low cardinality, target encoding for high cardinality, and frequency encoding as a regularized alternative."},{"number":4,"title":"Time-based feature extraction","description":"Get datetime feature extraction code for all common time signals.","code":"df[''hour''] = df[''ts''].dt.hour\ndf[''day_of_week''] = df[''ts''].dt.dayofweek\ndf[''is_weekend''] = (df[''day_of_week''] >= 5).astype(int)","language":"python"}]'::jsonb,
NULL,NULL,700,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'automated-report-builder','Automated Report Builder','Generate weekly business reports from database queries automatically','Build an automated weekly business reporting pipeline in TypeScript that runs database queries, formats HTML reports with WoW comparisons, and sends them via email or Slack.',
'data-analytics',NULL,ARRAY['reporting','automation','sql'],'intermediate',
199900,1900,false,
'[{"number":1,"title":"Define report queries","description":"Define the SQL queries for each metric in your report as a typed object.","code":"const queries = {\n  mrr: \"SELECT SUM(amount) FROM subscriptions WHERE status=''active''\",\n  newUsers: \"SELECT COUNT(*) FROM users WHERE created_at > NOW() - INTERVAL ''7d''\"\n};","language":"typescript"},{"number":2,"title":"Run queries and format HTML report","description":"Execute all queries in parallel, format the results into a structured HTML report with tables, metric cards, and a clear layout."},{"number":3,"title":"Send via email or Slack on schedule","description":"Configure the report to be delivered on a schedule via Resend email or Slack webhook with the HTML report as the body."},{"number":4,"title":"Add week-over-week comparison","description":"Add WoW delta calculation for every metric with trend arrows (up, down, flat) to give recipients instant context on performance direction."}]'::jsonb,
NULL,NULL,720,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'customer-segmentation-sql','Customer Segmentation SQL','RFM analysis: segment customers by Recency, Frequency, Monetary value','Build a complete RFM customer segmentation model in SQL — score every customer on Recency, Frequency, and Monetary value and export named segments for targeted campaigns.',
'data-analytics',NULL,ARRAY['rfm','segmentation','sql'],'intermediate',
99900,900,false,
'[{"number":1,"title":"Calculate R, F, M base metrics","description":"Aggregate orders to get recency (days since last order), frequency (total orders), and monetary (total spend) per customer.","code":"SELECT\n  customer_id,\n  DATEDIFF(NOW(), MAX(order_date)) AS recency,\n  COUNT(*) AS frequency,\n  SUM(amount) AS monetary\nFROM orders\nGROUP BY customer_id","language":"sql"},{"number":2,"title":"Score each dimension 1 to 5","description":"Use NTILE(5) to score each of recency, frequency, and monetary value from 1 to 5, with 5 being the best score for each dimension."},{"number":3,"title":"Combine into named segments","description":"Combine the three scores into composite RFM segments: Champions (555), Loyal Customers, Potential Loyalists, At Risk, and Lost customers."},{"number":4,"title":"Export segment lists","description":"Export each named segment as a customer list with contact details ready for targeted email campaign upload."}]'::jsonb,
NULL,NULL,690,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'churn-prediction-model','Churn Prediction Model','Build a SaaS churn prediction model with scikit-learn step by step','Build a complete SaaS churn prediction model using Gradient Boosting — from feature engineering through model training to evaluation and intervention trigger thresholds.',
'data-analytics',NULL,ARRAY['churn','machine-learning','python'],'advanced',
299900,2900,false,
'[{"number":1,"title":"Feature engineering for churn signals","description":"Engineer the predictive features: days_since_last_login, feature_usage_count in the last 30 days, support_tickets_open, and plan_type as a categorical."},{"number":2,"title":"Create binary churn label","description":"Label each user as churned (1) if they cancelled within the next 30 days or 0 if they remained active, creating a clean binary classification target."},{"number":3,"title":"Train Gradient Boosting model","description":"Train a Gradient Boosting classifier on the engineered features with 100 estimators.","code":"from sklearn.ensemble import GradientBoostingClassifier\nmodel = GradientBoostingClassifier(n_estimators=100)\nmodel.fit(X_train, y_train)","language":"python"},{"number":4,"title":"Evaluate and set intervention threshold","description":"Evaluate using precision, recall, and AUC-ROC. Set the intervention trigger at a predicted churn probability above 0.7 to prioritize outreach to highest-risk users."}]'::jsonb,
NULL,NULL,730,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'dashboard-query-builder','Dashboard Query Builder','Write optimized SQL for BI dashboards: Metabase, Grafana, Superset','Generate optimized SQL queries for any BI dashboard metric with date filter parameters, grouping, aggregations, and Metabase or Grafana variable syntax.',
'data-analytics',NULL,ARRAY['sql','bi','dashboards'],'intermediate',
0,0,true,
'[{"number":1,"title":"Describe the metric in plain English","description":"Describe the metric you need in plain English, for example: daily active users by country for the last 30 days."},{"number":2,"title":"Get optimized SQL query","description":"Receive a clean, optimized SQL query with proper date filtering, GROUP BY, and all required aggregations for your metric."},{"number":3,"title":"Optimization recommendations","description":"Get performance tips specific to your query: use materialized views for expensive aggregations, add query tags for tracking, and index recommendations."},{"number":4,"title":"BI tool variable syntax","description":"Receive the query adapted with the correct variable syntax for your BI tool. Example: WHERE date >= {{start_date}} for Metabase or $__timeFilter for Grafana.","code":"WHERE date >= {{start_date}}","language":"sql"}]'::jsonb,
NULL,NULL,740,0,0,false,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'etl-pipeline-designer','ETL Pipeline Designer','Design Python ETL pipelines with Airflow DAGs and error handling','Design production-ready Python ETL pipelines with Airflow DAGs — idempotent tasks, date macros, configurable retries, failure notifications, and dead letter tables.',
'data-analytics',NULL,ARRAY['etl','airflow','python'],'advanced',
199900,1900,false,
'[{"number":1,"title":"Define source, transformation, and destination","description":"Specify the data source (API, database, S3), the required transformations, and the destination table or system for the output data."},{"number":2,"title":"Airflow DAG structure","description":"Get the core Airflow DAG definition with schedule, start date, and default args.","code":"with DAG(\n  ''etl_daily'',\n  schedule=''0 2 * * *'',\n  start_date=days_ago(1)\n) as dag:","language":"python"},{"number":3,"title":"Idempotent tasks with date macro","description":"Every task uses the {{ ds }} Airflow date macro to make reruns safe — re-running a DAG for any date produces the same result without duplicating data."},{"number":4,"title":"Error handling and dead letter pattern","description":"Implement retries=3, on_failure_callback for email or Slack alerts, and a dead letter table pattern to capture and inspect failed records without losing data."}]'::jsonb,
NULL,NULL,660,0,0,false,true,false,NULL,true);
