-- Seed batch 1: ai-llm (12), iot (12), developer-tools (12)

-- ============================================================
-- CATEGORY: ai-llm (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'prompt-optimizer','Prompt Optimizer','Turn vague prompts into precise, high-output instructions','Master the art of prompt engineering with a repeatable 4-step framework. Identify task type, add role context, include few-shot examples, and validate with temperature 0.','ai-llm',NULL,
ARRAY['prompting','llm','productivity'],'beginner',0,0,true,
'[{"number":1,"title":"Identify the task type","description":"Classify your task as one of four core types before writing any prompt.","code":"const taskTypes = [\"classify\",\"generate\",\"extract\",\"reason\"] as const;","language":"typescript"},{"number":2,"title":"Add role and context prefix","description":"Prepend a role and context block to every prompt for consistent output.","code":"const optimized = `You are an expert {role}. Context: {context}\\nTask: {task}\\nOutput format: {format}`;","language":"typescript"},{"number":3,"title":"Add few-shot examples","description":"Include 2-3 examples so the model learns the exact output style you need.","code":"// Add 2-3 examples in your prompt\\n// Input: \"summarize this\" → Output: \"Create a 3-bullet executive summary...\"","language":"typescript"},{"number":4,"title":"Test with temperature 0","description":"Always validate a new prompt deterministically before using it in production.","code":"const res = await model.generateContent({contents:[{role:\"user\",parts:[{text:prompt}]}],generationConfig:{temperature:0}});","language":"typescript"}]'::jsonb,
NULL,NULL,900,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'rag-pipeline-builder','RAG Pipeline Builder','Build retrieval-augmented generation from scratch in 30 min','Learn to chunk documents, generate embeddings, store them in Qdrant, and retrieve context to ground LLM answers in real knowledge.','ai-llm',NULL,
ARRAY['rag','vector-db','embeddings'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Chunk documents","description":"Split source text into overlapping chunks so context is never cut mid-sentence.","code":"function chunkText(text:string,size=512,overlap=50){const chunks=[];for(let i=0;i<text.length;i+=size-overlap)chunks.push(text.slice(i,i+size));return chunks;}","language":"typescript"},{"number":2,"title":"Embed chunks via Gemini","description":"Generate a dense vector for each chunk using the text-embedding-004 model.","code":"const model=genAI.getGenerativeModel({model:\"text-embedding-004\"});const {embedding}=await model.embedContent(chunk);","language":"typescript"},{"number":3,"title":"Store in Qdrant","description":"Upsert each chunk with its embedding vector and source metadata.","code":"await client.upsert(collectionName,{points:[{id:uuid(),vector:embedding.values,payload:{text:chunk,source}}]});","language":"typescript"},{"number":4,"title":"Embed question and search","description":"Embed the user query and retrieve the top-5 most relevant chunks.","code":"const qEmbed=await model.embedContent(question);const results=await client.search(collectionName,{vector:qEmbed.embedding.values,limit:5});","language":"typescript"},{"number":5,"title":"Generate grounded answer","description":"Combine retrieved chunks as context and prompt the LLM to answer.","code":"const context=results.map(r=>r.payload.text).join(\"\\n\\n\");const answer=await chat.sendMessage(`Context:\\n${context}\\n\\nQuestion: ${question}`);","language":"typescript"}]'::jsonb,
NULL,NULL,950,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'agent-workflow-designer','Agent Workflow Designer','Design multi-step AI agent pipelines with tools and memory','Build production-grade multi-step agent systems using the ReAct loop pattern. Define specialist roles, wire up tools, and add persistent memory.','ai-llm',NULL,
ARRAY['agents','orchestration','llm'],'advanced',299900,2900,false,
'[{"number":1,"title":"Define agent roles","description":"Type each agent with a name, role description, allowed tools, and model tier.","code":"type Agent={name:string;role:string;tools:string[];model:\"flash\"|\"pro\"};","language":"typescript"},{"number":2,"title":"Build tool registry","description":"Register callable tools the agent can invoke during its reasoning loop.","code":"const tools={search:async(q:string)=>fetch(`/api/search?q=${q}`).then(r=>r.json()),calculator:(expr:string)=>eval(expr)};","language":"typescript"},{"number":3,"title":"Implement ReAct loop","description":"Alternate Thought → Action → Observation until the task is complete.","code":"while(!done){const thought=await llm.think(state);const action=await llm.act(thought);const obs=await tools[action.tool](action.input);state.observations.push(obs);}","language":"typescript"},{"number":4,"title":"Add memory store","description":"Persist facts per agent so later steps can reference earlier observations.","code":"const memory=new Map<string,string[]>();function remember(agent:string,fact:string){memory.get(agent)?.push(fact)??memory.set(agent,[fact]);}","language":"typescript"}]'::jsonb,
NULL,NULL,880,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'vector-db-schema-designer','Vector DB Schema Designer','Design Qdrant/Pinecone collections for production RAG workloads','Learn the right payload schema, collection config, named vectors for hybrid search, and payload indexes for lightning-fast filtered retrieval.','ai-llm',NULL,
ARRAY['qdrant','pinecone','vector-db'],'intermediate',99900,900,false,
'[{"number":1,"title":"Define payload schema","description":"Type your payload upfront so every chunk has consistent filterable metadata.","code":"interface VectorPayload{id:string;text:string;source:string;chunk_index:number;metadata:Record<string,unknown>;}","language":"typescript"},{"number":2,"title":"Create Qdrant collection","description":"Create a collection with Cosine distance and tuned segment count.","code":"await client.createCollection(\"docs\",{vectors:{size:768,distance:\"Cosine\"},optimizersConfig:{defaultSegmentNumber:2}});","language":"typescript"},{"number":3,"title":"Add named vectors for hybrid search","description":"Store both dense and sparse vectors in the same point for hybrid retrieval.","code":"await client.createCollection(\"docs\",{vectors:{dense:{size:768,distance:\"Cosine\"},sparse:{size:0,distance:\"Dot\"}}});","language":"typescript"},{"number":4,"title":"Set up payload index for filtering","description":"Index keyword fields so Qdrant can filter before computing vector similarity.","code":"await client.createPayloadIndex(\"docs\",{fieldName:\"source\",fieldSchema:\"keyword\"});","language":"typescript"}]'::jsonb,
NULL,NULL,720,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'llm-cost-optimizer','LLM Cost Optimizer','Cut your AI API bill by 60–80% with smart routing and caching','Use MD5 caching for repeated queries, complexity-based model routing, request batching, and spend tracking to slash your LLM costs.','ai-llm',NULL,
ARRAY['cost','optimization','caching'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Cache repeated queries","description":"Hash prompts with MD5 and serve cached responses before hitting the API.","code":"const cache=new Map<string,string>();async function cachedLLM(prompt:string){const key=crypto.createHash(\"md5\").update(prompt).digest(\"hex\");if(cache.has(key))return cache.get(key)!;const res=await llm(prompt);cache.set(key,res);return res;}","language":"typescript"},{"number":2,"title":"Route by complexity","description":"Send short, simple prompts to flash and only send complex analysis to pro.","code":"function routeModel(prompt:string):\"flash\"|\"pro\"{const tokens=prompt.split(\" \").length;return tokens<200&&!prompt.includes(\"analyze\")?\"flash\":\"pro\";}","language":"typescript"},{"number":3,"title":"Batch requests","description":"Queue prompts and flush in batches of 10 every 100ms to reduce overhead.","code":"const queue:Array<{prompt:string;resolve:(v:string)=>void}>=[];setInterval(async()=>{if(!queue.length)return;const batch=queue.splice(0,10);const results=await Promise.all(batch.map(b=>llm(b.prompt)));batch.forEach((b,i)=>b.resolve(results[i]!));},100);","language":"typescript"},{"number":4,"title":"Track spend per model","description":"Accumulate token costs per model tier so you can set budget alerts.","code":"const spend={flash:0,pro:0};function trackTokens(model:string,tokens:number){if(model===\"flash\")spend.flash+=tokens*0.000075/1000;else spend.pro+=tokens*0.00150/1000;}","language":"typescript"}]'::jsonb,
NULL,NULL,860,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'semantic-search-builder','Semantic Search Builder','Add AI-powered semantic search to any app in under 2 hours','Index your content as embeddings, expose a /search endpoint, and blend keyword and vector results for best-of-both recall.','ai-llm',NULL,
ARRAY['search','embeddings','nlp'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Index your content","description":"Embed every document and collect id, text, and vector together.","code":"async function indexDocuments(docs:string[]){const embeddings=await Promise.all(docs.map(d=>embed(d)));return embeddings.map((e,i)=>({id:i,text:docs[i],vector:e}));}","language":"typescript"},{"number":2,"title":"Store with metadata","description":"Upsert points into Qdrant with the raw text in the payload for display.","code":"await qdrant.upsert(\"search\",{points:indexed.map(d=>({id:d.id,vector:d.vector,payload:{text:d.text}}))});","language":"typescript"},{"number":3,"title":"Query endpoint","description":"Expose a GET /search route that embeds the query and returns top hits.","code":"app.get(\"/search\",async(req,res)=>{const q=req.query.q as string;const qVec=await embed(q);const hits=await qdrant.search(\"search\",{vector:qVec,limit:10});res.json(hits);});","language":"typescript"},{"number":4,"title":"Hybrid keyword and semantic merge","description":"Merge Fuse.js keyword hits with vector hits and deduplicate to top 10.","code":"const keywordHits=fuse.search(query).map(r=>r.item);const semanticHits=await vectorSearch(query);const merged=[...new Set([...keywordHits,...semanticHits])].slice(0,10);","language":"typescript"}]'::jsonb,
NULL,NULL,790,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'fine-tuning-dataset-creator','Fine-Tuning Dataset Creator','Generate high-quality training datasets from your existing content','Use an LLM to extract Q&A pairs from your docs, paraphrase for variety, format for fine-tuning APIs, and filter low-quality pairs automatically.','ai-llm',NULL,
ARRAY['fine-tuning','dataset','training'],'advanced',299900,2900,false,
'[{"number":1,"title":"Generate Q&A pairs from docs","description":"Prompt an LLM to produce structured Q&A pairs from each source document.","code":"async function generateQA(doc:string){const res=await llm(`Generate 5 Q&A pairs from:\\n${doc}\\nFormat: [{\"q\":\"...\",\"a\":\"...\"}]`);return JSON.parse(res);}","language":"typescript"},{"number":2,"title":"Augment with paraphrasing","description":"Generate n rephrasings of each question to increase dataset diversity.","code":"async function paraphrase(text:string,n=3){return Promise.all(Array(n).fill(0).map(()=>llm(`Rephrase: ${text}`)));}","language":"typescript"},{"number":3,"title":"Format for fine-tuning","description":"Convert pairs to the messages format expected by Gemini and OpenAI fine-tune endpoints.","code":"const formatted=pairs.map(p=>({messages:[{role:\"user\",content:p.q},{role:\"assistant\",content:p.a}]}));","language":"typescript"},{"number":4,"title":"Validate and filter quality","description":"Score each pair 1-10 and keep only those rated 7 or above.","code":"const scores=await Promise.all(pairs.map(p=>llm(`Rate 1-10 quality of: Q:${p.q} A:${p.a}. Reply with just a number.`)));const filtered=pairs.filter((_,i)=>parseInt(scores[i]!)>=7);","language":"typescript"}]'::jsonb,
NULL,NULL,680,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'chatbot-personality-designer','Chatbot Personality Designer','Design consistent AI personas with tone, voice and guardrails','Define a typed persona object, generate a system prompt from it, stress-test edge cases, and wire in an escalation path to human agents.','ai-llm',NULL,
ARRAY['chatbot','persona','prompt'],'beginner',0,0,true,
'[{"number":1,"title":"Define core traits","description":"Capture name, tone, vocabulary level, response length, and explicit avoids in a typed object.","code":"const persona={name:\"Aria\",tone:\"friendly-professional\",vocabulary:\"simple\",responseLength:\"concise\",avoids:[\"jargon\",\"negativity\"],always:[\"acknowledge first\",\"offer next step\"]};","language":"typescript"},{"number":2,"title":"Write system prompt","description":"Serialize the persona object into a natural-language system prompt.","code":"const systemPrompt=`You are ${persona.name}. Tone: ${persona.tone}. Always ${persona.always.join(\" and \")}. Never ${persona.avoids.join(\" or \")}.`;","language":"typescript"},{"number":3,"title":"Test edge cases","description":"Run the persona against rude, off-topic, competitor, and pricing-pressure inputs.","code":"const edgeCases=[\"rude question\",\"off-topic request\",\"competitor mention\",\"pricing pressure\"];for(const c of edgeCases)console.log(await chat(systemPrompt,c));","language":"typescript"},{"number":4,"title":"Add escalation logic","description":"Detect negative sentiment or explicit human requests and route to a live agent.","code":"if(sentiment(response)<-0.5||response.includes(\"speak to human\"))escalate(userId);","language":"typescript"}]'::jsonb,
NULL,NULL,640,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'multi-agent-orchestrator','Multi-Agent Orchestrator','Coordinate specialized AI agents to solve complex multi-step tasks','Define researcher, writer, and reviewer agents, build an LLM-powered router, pass context between agents, and handle failures with exponential backoff retry.','ai-llm',NULL,
ARRAY['agents','orchestration','automation'],'advanced',299900,2900,false,
'[{"number":1,"title":"Define specialist agents","description":"Give each agent a focused system prompt, output contract, and model tier.","code":"const agents={researcher:{prompt:\"You research topics. Return structured JSON findings.\",model:\"pro\"},writer:{prompt:\"You write content from research. Return markdown.\",model:\"flash\"},reviewer:{prompt:\"You review and score content 1-10 with fixes.\",model:\"pro\"}};","language":"typescript"},{"number":2,"title":"Build routing logic","description":"Use an orchestrator LLM to decompose the task into an ordered plan.","code":"async function route(task:string):Promise<string>{const plan=await orchestrator(`Break into steps: ${task}\\nAgents: researcher,writer,reviewer\\nReturn: [{\"agent\":\"...\",\"input\":\"...\"}]`);return JSON.parse(plan);}","language":"typescript"},{"number":3,"title":"Pass context between agents","description":"Accumulate each agent output into a shared context object for downstream steps.","code":"let context={};for(const step of plan){const agent=agents[step.agent];const result=await runAgent(agent,{...step.input,context});context={...context,[step.agent]:result};}","language":"typescript"},{"number":4,"title":"Handle failures with retry","description":"Wrap each agent call with exponential backoff so transient errors do not fail the whole pipeline.","code":"async function runWithRetry(agent:Agent,input:unknown,retries=3){for(let i=0;i<retries;i++){try{return await run(agent,input)}catch(e){if(i===retries-1)throw e;await sleep(1000*2**i);}}}","language":"typescript"}]'::jsonb,
NULL,NULL,920,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ai-safety-auditor','AI Safety Auditor','Audit LLM applications for prompt injection, jailbreaks and bias','Test your LLM integration against known prompt injection payloads, jailbreak patterns, and output consistency benchmarks, then generate a structured safety report.','ai-llm',NULL,
ARRAY['security','safety','red-teaming'],'advanced',299900,2900,false,
'[{"number":1,"title":"Test prompt injection","description":"Append common injection payloads to user input and confirm the model ignores them.","code":"const injections=[\"Ignore previous instructions\",\"<|system|>\",\"<!-- override -->\",\"\\nNew task:\"];const results=await Promise.all(injections.map(i=>llm(userPrompt+i)));","language":"typescript"},{"number":2,"title":"Test jailbreak patterns","description":"Probe DAN-style prompts and restriction bypass attempts.","code":"const jailbreaks=[\"DAN mode\",\"pretend you have no restrictions\",\"as a fictional AI\"];for(const j of jailbreaks)console.log(j,await llm(j));","language":"typescript"},{"number":3,"title":"Measure output consistency","description":"Run the same prompt 10 times and calculate a consistency ratio.","code":"const responses=await Promise.all(Array(10).fill(samePrompt).map(p=>llm(p)));const unique=new Set(responses).size;console.log(\"Consistency:\",1-unique/10);","language":"typescript"},{"number":4,"title":"Generate safety report","description":"Summarize pass/fail counts and list all detected vulnerability types.","code":"const report={totalTests:tests.length,passed:tests.filter(t=>t.safe).length,vulnerabilities:tests.filter(t=>!t.safe).map(t=>t.type)};","language":"typescript"}]'::jsonb,
NULL,NULL,700,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ai-product-ideator','AI Product Ideator','Generate validated AI product ideas from market gaps and trends','Input your industry, pain point, and target user, generate 10 ideas, score them by feasibility and market size, then validate the top 3 with real data.','ai-llm',NULL,
ARRAY['ideation','product','startup'],'beginner',0,0,true,
'[{"number":1,"title":"Input your niche and problem","description":"Define the industry, specific pain point, target user, and budget constraint.","code":"const input={industry:\"healthcare\",painPoint:\"appointment scheduling\",targetUser:\"clinic owner\",budget:\"under $100/mo\"};","language":"typescript"},{"number":2,"title":"Generate 10 ideas","description":"Prompt the LLM to produce structured ideas with name, problem, user, monetization, and build time.","code":"const ideas=await llm(`Generate 10 AI product ideas for: ${JSON.stringify(input)}\\nFor each: name, problem solved, target user, monetization, build time. JSON array.`);","language":"typescript"},{"number":3,"title":"Score by feasibility","description":"Have the model score each idea across four dimensions and rank the list.","code":"const scored=await llm(`Score each idea 1-10 for: market size, technical feasibility, competition, monetization. Input: ${ideas}`);","language":"typescript"},{"number":4,"title":"Validate top ideas","description":"Pull real search volume and competitor data for the top 3 before committing.","code":"const top3=scored.slice(0,3);for(const idea of top3){const keywords=await getSearchVolume(idea.name);const competitors=await searchCompetitors(idea.name);console.log({idea,keywords,competitors});}","language":"typescript"}]'::jsonb,
NULL,NULL,810,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ai-workflow-automator','AI Workflow Automator','Replace manual business processes with AI agents that run 24/7','Map a manual workflow, build a webhook trigger, implement each step as an AI agent function, and chain them with structured error handling and Slack notifications.','ai-llm',NULL,
ARRAY['automation','workflow','agents'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Map current workflow","description":"Model the existing manual process as a trigger plus ordered steps with a timeout budget.","code":"const workflow={trigger:\"new_email\",steps:[\"classify_intent\",\"extract_data\",\"lookup_crm\",\"draft_reply\",\"queue_review\"],timeout_ms:30000};","language":"typescript"},{"number":2,"title":"Build trigger handler","description":"Accept the triggering event via webhook and enqueue it for processing.","code":"app.post(\"/webhook/email\",async(req,res)=>{const email=req.body;const job=await queue.add(\"process-email\",email);res.json({jobId:job.id});});","language":"typescript"},{"number":3,"title":"Implement each step as agent","description":"Map each step name to an async AI function that transforms the data.","code":"const steps={classify_intent:async(email:Email)=>llm(`Classify: ${email.subject}\\n${email.body}\\nReturn: sales|support|spam|other`),extract_data:async(email:Email)=>llm(`Extract JSON: name,company,phone from:\\n${email.body}`)};","language":"typescript"},{"number":4,"title":"Chain with error handling","description":"Run steps sequentially, notify Slack on failure, and break the chain cleanly.","code":"for(const stepName of workflow.steps){try{result=await steps[stepName](result);}catch(e){await notify(\"slack\",`Step ${stepName} failed: ${e}`);break;}}","language":"typescript"}]'::jsonb,
NULL,NULL,870,0,0,true,true,false,NULL,true);

-- ============================================================
-- CATEGORY: iot (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'esp32-firmware-scaffold','ESP32 Firmware Scaffold','Production-ready ESP32 project: OTA, WiFi manager, MQTT, NVS','Scaffold a full PlatformIO project with WiFiManager for zero-touch provisioning, PubSubClient MQTT, ElegantOTA for remote updates, and a 5-second sensor publish loop.','iot',NULL,
ARRAY['esp32','firmware','arduino'],'intermediate',299900,2900,false,
'[{"number":1,"title":"Project structure","description":"Create the PlatformIO directory layout with feature-separated source folders.","code":"mkdir my-esp32 && cd my-esp32\nmkdir -p src/{wifi,mqtt,sensors,ota} include\ntouch platformio.ini src/main.cpp","language":"bash"},{"number":2,"title":"platformio.ini","description":"Configure the board, framework, and key library dependencies.","code":"[env:esp32dev]\nplatform=espressif32\nboard=esp32dev\nframework=arduino\nlib_deps =\n  knolleary/PubSubClient@^2.8\n  tzapu/WiFiManager@^2.0\n  ayushsharma82/ElegantOTA@^3.1","language":"ini"},{"number":3,"title":"WiFi and MQTT init","description":"Use WiFiManager for captive-portal provisioning then connect MQTT with the chip MAC as client ID.","code":"WiFiManager wm;\nwm.autoConnect(\"ESP32-Setup\");\nMQTTClient mqtt;\nmqtt.begin(\"broker.mqtt.io\",net);\nmqtt.connect(\"device-\"+String(ESP.getEfuseMac()));","language":"cpp"},{"number":4,"title":"OTA update handler","description":"Register ElegantOTA with auto-reboot and hook start/end callbacks for logging.","code":"ElegantOTA.begin(&server);\nElegantOTA.setAutoReboot(true);\nElegantOTA.onStart([](){Serial.println(\"OTA start\");});\nElegantOTA.onEnd([](){Serial.println(\"OTA done\");});","language":"cpp"},{"number":5,"title":"Sensor read loop","description":"Poll the DHT sensor every 5 seconds and publish temperature over MQTT.","code":"void loop(){\n  ElegantOTA.loop();\n  mqtt.loop();\n  if(millis()-lastRead>5000){\n    float t=dht.readTemperature();\n    mqtt.publish(\"/sensors/temp\",String(t));\n    lastRead=millis();\n  }\n}","language":"cpp"}]'::jsonb,
NULL,NULL,880,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'mqtt-broker-config','MQTT Broker Config','Production Mosquitto/EMQX setup with TLS, auth and ACLs','Install Mosquitto, configure TLS on port 8883, add password auth with per-device ACLs, then verify with publish and subscribe test commands.','iot',NULL,
ARRAY['mqtt','mosquitto','emqx'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Install Mosquitto","description":"Install and enable the Mosquitto broker on a Debian/Ubuntu server.","code":"sudo apt update && sudo apt install -y mosquitto mosquitto-clients\nsudo systemctl enable mosquitto","language":"bash"},{"number":2,"title":"TLS config","description":"Create the TLS listener config file with CA, cert, and key paths.","code":"# /etc/mosquitto/conf.d/tls.conf\nlistener 8883\ncafile /etc/mosquitto/certs/ca.crt\ncertfile /etc/mosquitto/certs/server.crt\nkeyfile /etc/mosquitto/certs/server.key\nrequire_certificate false","language":"bash"},{"number":3,"title":"Password auth and ACLs","description":"Create a password file and restrict each device to its own topic subtree.","code":"mosquitto_passwd -c /etc/mosquitto/passwd device1\n# /etc/mosquitto/acl\nuser device1\ntopic read sensors/#\ntopic write sensors/device1/#","language":"bash"},{"number":4,"title":"Test connection","description":"Verify TLS publish and subscribe work end-to-end from the command line.","code":"mosquitto_pub -h localhost -p 8883 --cafile ca.crt -u device1 -P pass1 -t sensors/device1/temp -m 23.5\nmosquitto_sub -h localhost -p 8883 --cafile ca.crt -u device1 -P pass1 -t sensors/#","language":"bash"}]'::jsonb,
NULL,NULL,720,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ble-gatt-profile-designer','BLE GATT Profile Designer','Design and implement custom BLE GATT profiles for ESP32/nRF52','Define custom service and characteristic UUIDs, create a BLE server with notify and write properties, implement command callbacks, and start advertising.','iot',NULL,
ARRAY['ble','gatt','esp32'],'advanced',299900,2900,false,
'[{"number":1,"title":"Define service UUIDs","description":"Generate and declare unique 128-bit UUIDs for your service and each characteristic.","code":"#define SERVICE_UUID  \"4fafc201-1fb5-459e-8fcc-c5c9c331914b\"\n#define CHAR_TEMP_UUID \"beb5483e-36e1-4688-b7f5-ea07361b26a8\"\n#define CHAR_CMD_UUID  \"d4e0b0f6-3b5e-4b5e-8b5e-4b5e8b5e4b5e\"","language":"cpp"},{"number":2,"title":"Create service and characteristics","description":"Instantiate the GATT server, service, and characteristics with the correct property flags.","code":"BLEServer* server=BLEDevice::createServer();\nBLEService* svc=server->createService(SERVICE_UUID);\nBLECharacteristic* tempChar=svc->createCharacteristic(CHAR_TEMP_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_NOTIFY);\ntempChar->addDescriptor(new BLE2902());","language":"cpp"},{"number":3,"title":"Implement write callbacks","description":"Subclass BLECharacteristicCallbacks to handle inbound command writes.","code":"class CmdCallbacks: public BLECharacteristicCallbacks{\n  void onWrite(BLECharacteristic* c){\n    std::string v=c->getValue();\n    if(v==\"reboot\")ESP.restart();\n    if(v==\"calibrate\")calibrateSensor();\n  }\n};","language":"cpp"},{"number":4,"title":"Start advertising","description":"Start the service and begin BLE advertising with the service UUID in the scan response.","code":"svc->start();\nBLEAdvertising* adv=BLEDevice::getAdvertising();\nadv->addServiceUUID(SERVICE_UUID);\nadv->setScanResponse(true);\nBLEDevice::startAdvertising();","language":"cpp"}]'::jsonb,
NULL,NULL,650,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'timescaledb-iot-schema','TimescaleDB IoT Schema','Time-series PostgreSQL schema for fleet IoT data at scale','Enable TimescaleDB, create a sensor_readings hypertable, configure 7-day compression and 90-day retention, add continuous hourly aggregates, and build a device registry.','iot',NULL,
ARRAY['timescaledb','postgresql','iot'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Enable extension and create hypertable","description":"Enable TimescaleDB and convert the sensor_readings table to a hypertable partitioned by time.","code":"CREATE EXTENSION IF NOT EXISTS timescaledb;\nCREATE TABLE sensor_readings(\n  time        TIMESTAMPTZ   NOT NULL,\n  device_id   TEXT          NOT NULL,\n  metric      TEXT          NOT NULL,\n  value       DOUBLE PRECISION,\n  tags        JSONB         DEFAULT \"{}\"\n);\nSELECT create_hypertable(''sensor_readings'',''time'');","language":"sql"},{"number":2,"title":"Add compression and retention","description":"Compress chunks older than 7 days and drop chunks older than 90 days automatically.","code":"ALTER TABLE sensor_readings SET(\n  timescaledb.compress,\n  timescaledb.compress_segmentby=''device_id,metric''\n);\nSELECT add_compression_policy(''sensor_readings'',INTERVAL ''7 days'');\nSELECT add_retention_policy(''sensor_readings'',INTERVAL ''90 days'');","language":"sql"},{"number":3,"title":"Continuous aggregates","description":"Create a materialised hourly average view that refreshes automatically.","code":"CREATE MATERIALIZED VIEW hourly_avg WITH(timescaledb.continuous) AS\nSELECT time_bucket(''1 hour'',time) AS hour,device_id,metric,\n  AVG(value) AS avg_val,MAX(value) AS max_val\nFROM sensor_readings GROUP BY 1,2,3;\nSELECT add_continuous_aggregate_policy(''hourly_avg'',\n  start_offset=>''3 hours'',end_offset=>''1 hour'',schedule_interval=>''1 hour'');","language":"sql"},{"number":4,"title":"Device registry table","description":"Create a normalised device registry with location and metadata as JSONB.","code":"CREATE TABLE devices(\n  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  serial           TEXT UNIQUE NOT NULL,\n  firmware_version TEXT,\n  location         JSONB,\n  last_seen        TIMESTAMPTZ,\n  metadata         JSONB DEFAULT ''{}''\n);","language":"sql"}]'::jsonb,
NULL,NULL,700,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'ota-update-pipeline','OTA Update Pipeline','Atomic over-the-air firmware updates with staged rollout and rollback','Build a /ota/manifest API, implement the ESP32 version-check at boot, use a hash-bucketing function for staged rollout percentages, and leverage the ESP32 A/B partition table for safe rollback.','iot',NULL,
ARRAY['ota','firmware','devops'],'advanced',299900,2900,false,
'[{"number":1,"title":"Version manifest endpoint","description":"Serve the latest firmware metadata including download URL and SHA-256 checksum.","code":"app.get(\"/ota/manifest\",async(req,res)=>{\n  const {device_id,current_version}=req.query;\n  const latest=await db.query(\"SELECT * FROM firmware_releases WHERE channel=$1 ORDER BY created_at DESC LIMIT 1\",[\"stable\"]);\n  res.json({current:current_version,latest:latest.version,url:latest.download_url,sha256:latest.checksum});\n});","language":"typescript"},{"number":2,"title":"ESP32 OTA check at boot","description":"On every boot compare the running version against the manifest and trigger OTA if behind.","code":"HTTPClient http;\nhttp.begin(\"https://api.yourdomain.com/ota/manifest?device_id=\"+deviceId+\"&current_version=\"+FIRMWARE_VERSION);\nDynamicJsonDocument doc(512);\ndeserializeJson(doc,http.getString());\nif(doc[\"latest\"].as<String>()!=FIRMWARE_VERSION)performOTA(doc[\"url\"],doc[\"sha256\"]);","language":"cpp"},{"number":3,"title":"Staged rollout logic","description":"Deterministically assign each device to a 0-100 bucket using its ID hash.","code":"function shouldReceiveUpdate(deviceId:string,rolloutPercent:number):boolean{\n  const hash=crypto.createHash(\"md5\").update(deviceId).digest(\"hex\");\n  const bucket=parseInt(hash.slice(0,2),16)/255*100;\n  return bucket<=rolloutPercent;\n}","language":"typescript"},{"number":4,"title":"Rollback on failure","description":"Use the ESP32 A/B OTA partition table so a failed update automatically boots the previous slot.","code":"const esp_partition_t* update=esp_ota_get_next_update_partition(NULL);\nesp_ota_handle_t handle;\nesp_ota_begin(update,OTA_SIZE_UNKNOWN,&handle);\n// ... write chunks ...\nesp_ota_end(handle);\nesp_ota_set_boot_partition(update);","language":"cpp"}]'::jsonb,
NULL,NULL,760,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'lorawan-device-setup','LoRaWAN Device Setup','Register and activate LoRaWAN devices on TTN/Chirpstack step by step','Provision OTAA keys, register the device on TTN via CLI, write a binary payload decoder, and forward uplinks to TimescaleDB via a webhook handler.','iot',NULL,
ARRAY['lorawan','ttn','iot'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Generate DevEUI and keys","description":"Hardcode APPEUI, DEVEUI, and APPKEY in PROGMEM for OTAA activation.","code":"static const u1_t PROGMEM APPEUI[8]={0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};\nstatic const u1_t PROGMEM DEVEUI[8]={0x01,0x23,0x45,0x67,0x89,0xAB,0xCD,0xEF};\nstatic const u1_t PROGMEM APPKEY[16]={0x2B,0x7E,0x15,0x16,0x28,0xAE,0xD2,0xA6,0xAB,0xF7,0x15,0x88,0x09,0xCF,0x4F,0x3C};","language":"cpp"},{"number":2,"title":"Register on TTN via CLI","description":"Create the end-device on The Things Network using ttn-lw-cli.","code":"ttn-lw-cli end-devices create --application-id my-app \\\n  --device-id my-device \\\n  --dev-eui 0123456789ABCDEF \\\n  --join-eui 0000000000000000 \\\n  --lorawan-version 1.0.3 \\\n  --frequency-plan-id EU_863_870_TTN","language":"bash"},{"number":3,"title":"Decode binary payload","description":"Parse a 4-byte payload into temperature, humidity, and battery voltage.","code":"function decodePayload(bytes:number[]){\n  const temp=(bytes[0]!<<8|bytes[1]!)/100;\n  const humidity=bytes[2]!/2;\n  const battery=(bytes[3]!+200)/100;\n  return{temp,humidity,battery};\n}","language":"typescript"},{"number":4,"title":"Forward uplinks to TimescaleDB","description":"Receive TTN webhook POSTs and insert decoded sensor values into the hypertable.","code":"app.post(\"/ttn/webhook\",async(req,res)=>{\n  const{device_id,decoded_payload,received_at}=req.body.uplink_message;\n  await db.query(\"INSERT INTO sensor_readings VALUES($1,$2,$3,$4)\",\n    [received_at,device_id,\"temp\",decoded_payload.temp]);\n  res.sendStatus(200);\n});","language":"typescript"}]'::jsonb,
NULL,NULL,580,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'modbus-rtu-driver','Modbus RTU Driver','Read and write Modbus RTU/TCP registers from Node.js or C','Connect to a serial Modbus slave, read holding registers, write coils and registers, and poll on a 5-second interval with error recovery.','iot',NULL,
ARRAY['modbus','industrial','protocols'],'advanced',299900,2900,false,
'[{"number":1,"title":"Install modbus-serial","description":"Add the modbus-serial npm package to your Node.js project.","code":"npm install modbus-serial","language":"bash"},{"number":2,"title":"Read holding registers","description":"Open the serial port and read 10 consecutive holding registers from slave ID 1.","code":"import ModbusRTU from \"modbus-serial\";\nconst client=new ModbusRTU();\nawait client.connectRTUBuffered(\"/dev/ttyUSB0\",{baudRate:9600,dataBits:8,parity:\"none\",stopBits:1});\nclient.setID(1);\nconst data=await client.readHoldingRegisters(0,10);\nconsole.log(data.data);","language":"typescript"},{"number":3,"title":"Write coils and registers","description":"Toggle a coil, write a single register, and write a block of registers in one sequence.","code":"await client.writeCoil(0,true);\nawait client.writeRegister(10,1234);\nawait client.writeRegisters(20,[100,200,300]);","language":"typescript"},{"number":4,"title":"Poll and store with error handling","description":"Read current, voltage, and power every 5 seconds and insert into the database.","code":"setInterval(async()=>{\n  try{\n    const regs=await client.readHoldingRegisters(0,5);\n    const[current,voltage,power]=regs.data;\n    await db.insert({time:new Date(),current,voltage,power});\n  }catch(e){console.error(\"Modbus read error\",e);}\n},5000);","language":"typescript"}]'::jsonb,
NULL,NULL,540,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'edge-ai-tflite-setup','Edge AI with TFLite','Deploy TensorFlow Lite models on ESP32/Raspberry Pi for on-device inference','Convert a Keras model to quantized TFLite, embed it as a C array, run inference on the ESP32 using TFLite Micro, and benchmark the inference latency.','iot',NULL,
ARRAY['tflite','edge-ai','esp32'],'advanced',299900,2900,false,
'[{"number":1,"title":"Convert model to TFLite","description":"Load a Keras model and convert it to a quantized TFLite flatbuffer.","code":"import tensorflow as tf\nmodel=tf.keras.models.load_model(\"model.h5\")\nconverter=tf.lite.TFLiteConverter.from_keras_model(model)\nconverter.optimizations=[tf.lite.Optimize.DEFAULT]\ntflite_model=converter.convert()\nopen(\"model.tflite\",\"wb\").write(tflite_model)","language":"python"},{"number":2,"title":"Convert to C array","description":"Use xxd to produce a C source file that embeds the model bytes.","code":"xxd -i model.tflite > model_data.cc","language":"bash"},{"number":3,"title":"ESP32 inference code","description":"Allocate the tensor arena, load the model, set input, invoke, and read output.","code":"#include \"tensorflow/lite/micro/micro_interpreter.h\"\n#include \"model_data.h\"\nconstexpr int kTensorArenaSize=50*1024;\nuint8_t tensor_arena[kTensorArenaSize];\ntflite::MicroInterpreter interpreter(model,resolver,tensor_arena,kTensorArenaSize);\ninterpreter.AllocateTensors();\ninterpreter.input(0)->data.f[0]=sensorValue;\ninterpreter.Invoke();\nfloat result=interpreter.output(0)->data.f[0];","language":"cpp"},{"number":4,"title":"Benchmark inference time","description":"Wrap the Invoke call with micros() to measure inference latency in microseconds.","code":"unsigned long start=micros();\ninterpreter.Invoke();\nunsigned long elapsed=micros()-start;\nSerial.printf(\"Inference: %luus (%.1fms)\\n\",elapsed,elapsed/1000.0);","language":"cpp"}]'::jsonb,
NULL,NULL,720,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'iot-security-hardening','IoT Security Hardening','Secure boot, encrypted storage, mTLS and certificate pinning for ESP32','Enable secure boot V2 and flash encryption via sdkconfig, store secrets in encrypted NVS, configure mTLS with client certificates, and add connection-failure backoff with deep sleep.','iot',NULL,
ARRAY['security','esp32','tls'],'advanced',299900,2900,false,
'[{"number":1,"title":"Enable secure boot","description":"Configure secure boot V2 in sdkconfig and generate the signing key.","code":"# sdkconfig\nCONFIG_SECURE_BOOT=y\nCONFIG_SECURE_BOOT_SIGNING_KEY=\"secure_boot_signing_key.pem\"\nCONFIG_SECURE_SIGNED_ON_BOOT=y\n# Generate key:\nespsecure.py generate_signing_key --version 2 secure_boot_signing_key.pem","language":"bash"},{"number":2,"title":"Flash encryption and encrypted NVS","description":"Enable flash encryption in development mode; NVS stores all secrets encrypted at rest.","code":"// sdkconfig\nCONFIG_FLASH_ENCRYPTION_ENABLED=y\nCONFIG_FLASH_ENCRYPTION_MODE_DEVELOPMENT=y\n// In firmware:\nnvs_flash_init();\nnvs_open(\"storage\",NVS_READWRITE,&nvs);\nnvs_set_str(nvs,\"api_key\",apiKey);","language":"cpp"},{"number":3,"title":"mTLS certificate pinning","description":"Load the server CA, client certificate, and private key into WiFiClientSecure for mutual TLS.","code":"WiFiClientSecure net;\nnet.setCACert(root_ca);\nnet.setCertificate(client_cert);\nnet.setPrivateKey(client_key);\nmqttClient.begin(\"broker.yourdomain.com\",8883,net);","language":"cpp"},{"number":4,"title":"Connection failure backoff","description":"Count consecutive MQTT failures in NVS and deep-sleep for 5 minutes after 5 failures.","code":"static int failCount=0;\nif(!mqtt.connected()){failCount++;\n  if(failCount>5){\n    nvs_set_u32(nvs,\"fail_count\",failCount);\n    esp_deep_sleep(300000000ULL);\n  }\n}else{failCount=0;}","language":"cpp"}]'::jsonb,
NULL,NULL,660,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'canbus-decoder','CAN Bus Decoder','Parse and log CAN bus messages from vehicles or industrial equipment','Wire an MCP2515 to ESP32 over SPI, read CAN frames in the loop, decode OBD-II PIDs for RPM, speed, and coolant, then forward frames as JSON over MQTT.','iot',NULL,
ARRAY['canbus','automotive','industrial'],'advanced',299900,2900,false,
'[{"number":1,"title":"Connect MCP2515 to ESP32","description":"Initialise the MCP2515 SPI CAN controller at 500 kbps in normal mode.","code":"#include <mcp_can.h>\nMCP_CAN CAN(5); // CS=GPIO5\nvoid setup(){\n  CAN.begin(MCP_ANY,500000,MCP_8MHZ);\n  CAN.setMode(MCP_NORMAL);\n}","language":"cpp"},{"number":2,"title":"Read and decode frames","description":"Poll for available messages and print the ID and hex data bytes.","code":"long unsigned int rxId;\nunsigned char len,buf[8];\nif(CAN_MSGAVAIL==CAN.checkReceive()){\n  CAN.readMsgBuf(&rxId,&len,buf);\n  Serial.printf(\"ID: 0x%03X Len:%d \",rxId,len);\n  for(int i=0;i<len;i++)Serial.printf(\"%02X \",buf[i]);\n}","language":"cpp"},{"number":3,"title":"Decode OBD-II PIDs","description":"Implement helper functions for the most common OBD-II PIDs.","code":"float decodeRPM(uint8_t* buf){return((buf[0]*256.0+buf[1])/4.0);}\nfloat decodeSpeed(uint8_t* buf){return buf[0];}\nfloat decodeCoolantTemp(uint8_t* buf){return buf[0]-40;}\n// PID 0x0C=RPM, 0x0D=Speed, 0x05=Coolant","language":"cpp"},{"number":4,"title":"Publish frames as JSON over MQTT","description":"Serialise each frame as JSON and publish to the /can/frames topic.","code":"String json=\"{\\\"ts\\\":\"+String(millis())+\",\\\"id\\\":\\\"\"+String(rxId,HEX)+\"\\\",\\\"data\\\":[\"+dataStr+\"]}\";\nmqtt.publish(\"/can/frames\",json.c_str());","language":"cpp"}]'::jsonb,
NULL,NULL,500,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'zigbee-mesh-planner','Zigbee Mesh Planner','Design Zigbee mesh topology, device roles and network addressing','Plan coordinator, router, and end-device counts, configure Zigbee2MQTT with the right channel and PAN ID to avoid WiFi overlap, pair devices, and write an occupancy automation rule.','iot',NULL,
ARRAY['zigbee','mesh','iot'],'intermediate',199900,1900,false,
'[{"number":1,"title":"Device role planning","description":"Define coordinator, router, and end-device counts and placement strategy.","code":"const network={\n  coordinator:{count:1,device:\"CC2652P\",role:\"collects all data, connects to server\"},\n  routers:{count:4,device:\"SONOFF ZBMINI\",placement:\"spread for 15m coverage per hop\"},\n  endDevices:{count:20,device:\"Xiaomi sensors\",battery:\"AA, 2yr life\"}\n};","language":"typescript"},{"number":2,"title":"PANID and channel setup","description":"Configure Zigbee2MQTT to use channel 25 to avoid overlap with WiFi channels 1, 6, and 11.","code":"# config.yaml\npermit_join: true\nmqtt:\n  base_topic: zigbee2mqtt\n  server: mqtt://localhost\nserial:\n  port: /dev/ttyACM0\nadvanced:\n  pan_id: 0x1234\n  channel: 25","language":"yaml"},{"number":3,"title":"Pair devices","description":"Open a 2-minute pairing window via MQTT and monitor for join events.","code":"mosquitto_pub -t zigbee2mqtt/bridge/request/permit_join -m ''{\"value\":true,\"time\":120}''\n# Hold device button 5s until LED blinks\nmosquitto_sub -t zigbee2mqtt/# -v | grep device_joined","language":"bash"},{"number":4,"title":"Occupancy automation rule","description":"Subscribe to the sensor topic and turn a light ON whenever occupancy is detected.","code":"mosquitto_sub -t \"zigbee2mqtt/sensor_1\" | jq -r ''.occupancy'' | while read state; do\n  if [ \"$state\" = \"true\" ]; then\n    mosquitto_pub -t \"zigbee2mqtt/light_1/set\" -m ''{\"state\":\"ON\"}''\n  fi\ndone","language":"bash"}]'::jsonb,
NULL,NULL,480,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'digital-twin-schema','Digital Twin Schema','Design PostgreSQL + TimescaleDB schema for industrial digital twins','Model assets with typed spec JSONB, ingest real-time telemetry into a partitioned hypertable, track alerts with severity levels, and surface health KPIs in a live view.','iot',NULL,
ARRAY['digital-twin','timescaledb','industrial'],'advanced',299900,2900,false,
'[{"number":1,"title":"Asset model","description":"Create the assets table with manufacturer details, install date, and a spec JSONB column for rated parameters.","code":"CREATE TABLE assets(\n  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  asset_type    TEXT NOT NULL,\n  serial_number TEXT UNIQUE NOT NULL,\n  manufacturer  TEXT,\n  model         TEXT,\n  install_date  DATE,\n  location      JSONB,\n  spec          JSONB\n);","language":"sql"},{"number":2,"title":"Real-time telemetry hypertable","description":"Create a telemetry hypertable partitioned by time and asset_id for parallel scans.","code":"CREATE TABLE telemetry(\n  time      TIMESTAMPTZ      NOT NULL,\n  asset_id  UUID REFERENCES assets(id),\n  metric    TEXT             NOT NULL,\n  value     DOUBLE PRECISION NOT NULL,\n  quality   SMALLINT         DEFAULT 192\n);\nSELECT create_hypertable(''telemetry'',''time'',partitioning_column=>''asset_id'',number_partitions=>4);","language":"sql"},{"number":3,"title":"Anomaly alerts table","description":"Store triggered alerts with severity, actual value, threshold, and resolution timestamp.","code":"CREATE TABLE alerts(\n  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  asset_id     UUID REFERENCES assets(id),\n  metric       TEXT NOT NULL,\n  severity     TEXT CHECK(severity IN(''info'',''warning'',''critical'')),\n  value        DOUBLE PRECISION,\n  threshold    DOUBLE PRECISION,\n  triggered_at TIMESTAMPTZ DEFAULT now(),\n  resolved_at  TIMESTAMPTZ\n);","language":"sql"},{"number":4,"title":"Asset health view","description":"Join assets, last-hour telemetry, and recent critical alerts into a single health view.","code":"CREATE VIEW asset_health AS\nSELECT a.id,a.serial_number,a.asset_type,\n  AVG(t.value) FILTER(WHERE t.metric=''vibration'') AS avg_vibration,\n  MAX(t.value) FILTER(WHERE t.metric=''temperature'') AS max_temp,\n  COUNT(al.id) FILTER(WHERE al.severity=''critical'' AND al.triggered_at>now()-INTERVAL''7d'') AS critical_alerts_7d\nFROM assets a\nLEFT JOIN telemetry t ON a.id=t.asset_id AND t.time>now()-INTERVAL''1h''\nLEFT JOIN alerts al ON a.id=al.asset_id\nGROUP BY a.id,a.serial_number,a.asset_type;","language":"sql"}]'::jsonb,
NULL,NULL,620,0,0,true,true,false,NULL,true);

-- ============================================================
-- CATEGORY: developer-tools (12 skills)
-- ============================================================

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'code-reviewer','Code Reviewer','Security-focused AI code review: OWASP top 10, type safety, performance','Run an AI-powered review that catches SQL injection, N+1 queries, and unsafe any usage in seconds. Integrate into CI to block issues before they reach production.','developer-tools',NULL,
ARRAY['code-review','security','typescript'],'beginner',0,0,true,
'[{"number":1,"title":"Run against a file","description":"Point the CLI at any TypeScript source file to get an instant review.","code":"npx @addonweb/claude-toolkit review ./src/api/auth.ts","language":"bash"},{"number":2,"title":"Review output structure","description":"The tool returns structured JSON with categorised findings and a quality score.","code":"// Output:\n{\n  security:  [{severity:\"high\",issue:\"SQL injection\",line:45,fix:\"Use parameterized queries\"}],\n  performance:[{issue:\"N+1 query\",line:78,fix:\"Add eager loading\"}],\n  types:     [{issue:\"any usage\",line:12,fix:\"Replace with specific type\"}],\n  score: 7.2\n}","language":"typescript"},{"number":3,"title":"Apply a fix","description":"Compare the vulnerable pattern against the parameterised-query safe version.","code":"// Before (vulnerable):\nconst user=await db.query(`SELECT * FROM users WHERE id=${userId}`);\n// After (safe):\nconst user=await db.query(\"SELECT * FROM users WHERE id=$1\",[userId]);","language":"typescript"},{"number":4,"title":"Run in CI","description":"Add the review step to GitHub Actions and fail the build on medium-severity or above.","code":"# .github/workflows/review.yml\n- name: AI Code Review\n  run: npx @addonweb/claude-toolkit review ./src --format=github-comment --min-severity=medium","language":"yaml"}]'::jsonb,
NULL,NULL,950,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'sql-query-builder','SQL Query Builder','Write SQL in plain English — handles JOINs, CTEs, window functions','Describe what you need in plain language, get production-ready PostgreSQL back, refine with follow-up instructions, and execute directly from your codebase.','developer-tools',NULL,
ARRAY['sql','natural-language','postgresql'],'beginner',0,0,true,
'[{"number":1,"title":"Describe your query","description":"Pass a plain-English description plus your table schema to the skill.","code":"const result=await runSkill(sqlQueryBuilder,{\n  description:\"Get top 10 customers by revenue in the last 30 days with their order count\",\n  schema:\"customers(id,name,email), orders(id,customer_id,total,created_at)\",\n  dialect:\"postgresql\"\n});","language":"typescript"},{"number":2,"title":"Get generated SQL","description":"The skill returns valid, formatted SQL ready to paste or execute.","code":"SELECT c.name,c.email,COUNT(o.id) AS order_count,SUM(o.total) AS revenue\nFROM customers c\nJOIN orders o ON c.id=o.customer_id\nWHERE o.created_at>=NOW()-INTERVAL ''30 days''\nGROUP BY c.id,c.name,c.email\nORDER BY revenue DESC\nLIMIT 10;","language":"sql"},{"number":3,"title":"Iterate with a follow-up","description":"Refine the previous query using plain-English instructions without rewriting from scratch.","code":"const refined=await runSkill(sqlQueryBuilder,{\n  description:\"Same query but include customers with no orders (show 0s)\",\n  previousQuery:result.data.sql,\n  schema:\"customers(id,name,email), orders(id,customer_id,total,created_at)\"\n});","language":"typescript"},{"number":4,"title":"Run and validate","description":"Execute the generated query and log the row count and duration.","code":"const rows=await db.query(result.data.sql);\nconsole.log(`Returned ${rows.length} rows in ${rows.duration}ms`);","language":"typescript"}]'::jsonb,
NULL,NULL,900,0,0,true,true,true,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'test-generator','Test Generator','Generate unit and integration tests from source code automatically','Feed source code to the skill and get a complete Vitest test suite covering happy paths, edge cases, and error handling — ready to run with zero edits.','developer-tools',NULL,
ARRAY['testing','vitest','jest'],'beginner',0,0,true,
'[{"number":1,"title":"Point at a function","description":"Pass the raw source file and specify the desired coverage categories.","code":"const tests=await runSkill(testGenerator,{\n  code:fs.readFileSync(\"./src/lib/pricing.ts\",\"utf8\"),\n  framework:\"vitest\",\n  coverage:[\"happy-path\",\"edge-cases\",\"error-handling\"]\n});","language":"typescript"},{"number":2,"title":"Generated test output","description":"The skill returns a complete describe block with typed imports and assertions.","code":"import{describe,it,expect}from\"vitest\";\nimport{calculateTotal}from\"../lib/pricing\";\ndescribe(\"calculateTotal\",()=>{\n  it(\"applies GST correctly\",()=>expect(calculateTotal(1000,18)).toBe(1180));\n  it(\"handles zero amount\",()=>expect(calculateTotal(0,18)).toBe(0));\n  it(\"throws on negative amount\",()=>expect(()=>calculateTotal(-100,18)).toThrow());\n});","language":"typescript"},{"number":3,"title":"Run tests","description":"Execute the test suite with coverage reporting.","code":"npx vitest run --coverage","language":"bash"},{"number":4,"title":"Add to CI","description":"Wire test and coverage scripts into package.json for CI consumption.","code":"// package.json\n\"scripts\":{\"test\":\"vitest run\",\"test:coverage\":\"vitest run --coverage\"}","language":"json"}]'::jsonb,
NULL,NULL,870,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'docker-compose-builder','Docker Compose Builder','Generate production-ready docker-compose.yml from service descriptions','Describe your stack and the skill returns a compose file with health checks, named volumes, isolated networks, and env-file wiring — no boilerplate hunting.','developer-tools',NULL,
ARRAY['docker','devops','containers'],'beginner',0,0,true,
'[{"number":1,"title":"Describe your stack","description":"List your services and the features you need in the generated file.","code":"const result=await runSkill(dockerComposeBuilder,{\n  services:[\"nextjs-app\",\"postgresql\",\"redis\",\"nginx\"],\n  environment:\"production\",\n  features:[\"health-checks\",\"volumes\",\"networks\",\"env-files\"]\n});","language":"typescript"},{"number":2,"title":"Generated compose file","description":"The skill returns a complete docker-compose.yml with correct dependency ordering.","code":"services:\n  app:\n    build: .\n    env_file: .env\n    depends_on:\n      db:\n        condition: service_healthy\n    networks: [backend]\n  db:\n    image: postgres:16\n    healthcheck:\n      test: [\"CMD\",\"pg_isready\",\"-U\",\"postgres\"]\n      interval: 10s\n    volumes: [postgres_data:/var/lib/postgresql/data]","language":"yaml"},{"number":3,"title":"Start services","description":"Bring the stack up in detached mode and tail app logs.","code":"docker compose up -d\ndocker compose logs -f app","language":"bash"},{"number":4,"title":"Production checklist","description":"Verify no unnecessary ports are exposed and scan images for CVEs.","code":"docker compose config | grep \"ports:\"\ndocker scout cves myapp:latest","language":"bash"}]'::jsonb,
NULL,NULL,780,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'github-actions-pipeline','GitHub Actions Pipeline','CI/CD pipeline: lint, test, build, deploy to Vercel/Railway/Fly','Create a full GitHub Actions workflow that runs type-check, lint, and tests on every PR, then deploys to Vercel production on merge to main.','developer-tools',NULL,
ARRAY['github-actions','ci-cd','devops'],'intermediate',99900,900,false,
'[{"number":1,"title":"Create workflow file","description":"Scaffold the workflow file triggered on push to main and dev and on all PRs.","code":"mkdir -p .github/workflows\ncat > .github/workflows/ci.yml << ''EOF''\nname: CI\non:\n  push:\n    branches: [main,dev]\n  pull_request:\n    branches: [main]\nEOF","language":"bash"},{"number":2,"title":"Lint and test job","description":"Set up Node 20 with npm cache, then run lint, type-check, and tests with coverage.","code":"jobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: {node-version: \"20\", cache: \"npm\"}\n      - run: npm ci\n      - run: npm run lint\n      - run: npm run type-check\n      - run: npm test -- --coverage","language":"yaml"},{"number":3,"title":"Deploy to Vercel on main","description":"Use the official Vercel action to deploy to production only when tests pass on main.","code":"  deploy:\n    needs: test\n    if: github.ref==''refs/heads/main''\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: amondnet/vercel-action@v25\n        with:\n          vercel-token: ${{secrets.VERCEL_TOKEN}}\n          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}\n          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}\n          vercel-args: ''--prod''","language":"yaml"},{"number":4,"title":"Add status badge","description":"Paste the workflow badge into your README for instant build-status visibility.","code":"[![CI](https://github.com/org/repo/actions/workflows/ci.yml/badge.svg)](https://github.com/org/repo/actions/workflows/ci.yml)","language":"markdown"}]'::jsonb,
NULL,NULL,820,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'database-migration-planner','Database Migration Planner','Plan safe zero-downtime schema migrations for production PostgreSQL','Analyse table sizes, add columns without locking, create indexes concurrently, and check for long-running queries before executing any DDL.','developer-tools',NULL,
ARRAY['postgresql','migrations','devops'],'advanced',199900,1900,false,
'[{"number":1,"title":"Analyse existing schema","description":"Query pg_stat_user_tables to understand table sizes and row counts before planning DDL.","code":"SELECT schemaname,tablename,\n  pg_size_pretty(pg_total_relation_size(schemaname||''.''||tablename)) AS size,\n  n_live_tup AS row_count\nFROM pg_stat_user_tables\nORDER BY pg_total_relation_size(schemaname||''.''||tablename) DESC;","language":"sql"},{"number":2,"title":"Add column safely","description":"In PG11+ ADD COLUMN with a DEFAULT is instant. For NOT NULL columns backfill before adding the constraint.","code":"-- Safe on large tables:\nALTER TABLE users ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT ''{}'';\n-- NOT NULL pattern:\nALTER TABLE users ADD COLUMN phone TEXT;\nUPDATE users SET phone='''' WHERE phone IS NULL;\nALTER TABLE users ALTER COLUMN phone SET NOT NULL;","language":"sql"},{"number":3,"title":"Create index without blocking writes","description":"CONCURRENTLY builds the index without holding an exclusive lock on the table.","code":"CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_email ON users(email);\nCREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_customer\n  ON orders(customer_id) WHERE status!=''deleted'';","language":"sql"},{"number":4,"title":"Check for conflicting queries","description":"Confirm no long-running transactions will conflict with your DDL before deploying.","code":"SELECT pid,now()-query_start AS duration,query\nFROM pg_stat_activity\nWHERE state=''active'' AND query_start<now()-INTERVAL ''30 seconds''\nORDER BY duration DESC;","language":"sql"}]'::jsonb,
NULL,NULL,640,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'api-docs-generator','API Docs Generator','Generate OpenAPI 3.0 spec and markdown docs from your route handlers','Point the skill at your Next.js or Fastify route files and get a complete OpenAPI 3.0 spec, a Swagger/Redoc UI endpoint, and a generated TypeScript client SDK.','developer-tools',NULL,
ARRAY['openapi','swagger','documentation'],'beginner',99900,900,false,
'[{"number":1,"title":"Point at route files","description":"Pass a glob of route files plus API metadata to the skill.","code":"const spec=await runSkill(apiDocsGenerator,{\n  routeFiles:[\"src/app/api/**/*.ts\"],\n  framework:\"nextjs\",\n  title:\"AddonWeb Toolkit API\",\n  version:\"1.0.0\",\n  baseUrl:\"https://addon90days.vercel.app\"\n});","language":"typescript"},{"number":2,"title":"Generated OpenAPI spec","description":"The skill returns a valid OpenAPI 3.0 YAML with paths, parameters, and response schemas.","code":"openapi: \"3.0.0\"\ninfo:\n  title: AddonWeb Toolkit API\n  version: 1.0.0\npaths:\n  /api/skills:\n    get:\n      summary: List skills\n      parameters:\n        - name: category\n          in: query\n          schema: {type: string}\n      responses:\n        \"200\":\n          description: Skills list","language":"yaml"},{"number":3,"title":"Serve with Redoc","description":"Mount the spec as JSON and serve a zero-dependency Redoc page.","code":"app.get(\"/openapi.json\",(_,res)=>res.json(spec));\napp.get(\"/docs\",(_,res)=>res.send(`<html><body><redoc spec-url=''/openapi.json''></redoc><script src=''https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js''></script></body></html>`));","language":"typescript"},{"number":4,"title":"Auto-generate TypeScript client","description":"Use openapi-typescript to generate type-safe client types from the spec.","code":"npx openapi-typescript openapi.json --output src/types/api.d.ts","language":"bash"}]'::jsonb,
NULL,NULL,700,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'regex-builder','Regex Builder','Generate and explain regular expressions from plain English descriptions','Describe the pattern you need, get a regex with step-by-step explanation and test results, then drop it directly into form validation or parsing logic.','developer-tools',NULL,
ARRAY['regex','validation','parsing'],'beginner',0,0,true,
'[{"number":1,"title":"Describe your pattern","description":"Pass a plain-English description and example inputs that should match or fail.","code":"const result=await runSkill(regexBuilder,{\n  description:\"Match Indian mobile numbers: optional +91 or 0, then 10 digits starting with 6-9\",\n  testCases:[\"9876543210\",\"+919876543210\",\"09876543210\",\"1234567890\"]\n});","language":"typescript"},{"number":2,"title":"Get pattern and explanation","description":"The skill returns the regex and a line-by-line explanation of each component.","code":"{\n  pattern: /^(?:\\+91|0)?[6-9]\\d{9}$/,\n  explanation: [\n    \"^ - start of string\",\n    \"(?:\\\\+91|0)? - optional +91 or 0 prefix\",\n    \"[6-9] - first digit must be 6,7,8, or 9\",\n    \"\\\\d{9} - exactly 9 more digits\",\n    \"$ - end of string\"\n  ],\n  testResults:{pass:3,fail:1}\n}","language":"typescript"},{"number":3,"title":"Use in form validation","description":"Drop the pattern into a typed validation function that strips spaces and dashes.","code":"const indianMobile=/^(?:\\+91|0)?[6-9]\\d{9}$/;\nfunction validatePhone(phone:string):boolean{\n  return indianMobile.test(phone.replace(/[\\s-]/g,\"\"));\n}","language":"typescript"},{"number":4,"title":"Unit test","description":"Write Vitest assertions covering valid numbers and known invalid inputs.","code":"import{expect,test}from\"vitest\";\ntest(\"valid Indian mobiles\",()=>{\n  expect(validatePhone(\"9876543210\")).toBe(true);\n  expect(validatePhone(\"+91 98765 43210\")).toBe(true);\n  expect(validatePhone(\"1234567890\")).toBe(false);\n});","language":"typescript"}]'::jsonb,
NULL,NULL,760,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'error-debugger','Error Debugger','Paste a stack trace, get root cause analysis and fix in 30 seconds','Feed a stack trace and source context to the skill and get back the root cause, the affected line, a ready-to-apply code fix, and a prevention tip.','developer-tools',NULL,
ARRAY['debugging','errors','productivity'],'beginner',0,0,true,
'[{"number":1,"title":"Paste your error","description":"Pass the full stack trace and the relevant source file to the skill.","code":"const analysis=await runSkill(errorDebugger,{\n  stackTrace:`TypeError: Cannot read properties of undefined (reading ''map'')\n    at UserList (src/components/UserList.tsx:23:18)`,\n  codeContext:fs.readFileSync(\"src/components/UserList.tsx\",\"utf8\")\n});","language":"typescript"},{"number":2,"title":"Get root cause and fix","description":"The skill returns a structured object with root cause, line number, fix, and prevention advice.","code":"{\n  rootCause: \"users prop is undefined on first render before data loads\",\n  line: 23,\n  fix: \"Add null check: (users ?? []).map(...) or add loading state\",\n  codeFix: \"const list=users?.map(u=><UserRow key={u.id} user={u}/>)??<Spinner/>\",\n  prevention: \"Define default prop value: users: User[] = []\"\n}","language":"typescript"},{"number":3,"title":"Apply the fix","description":"Swap the unsafe map call for the null-safe version with a loading fallback.","code":"// Before:\nreturn users.map(user=><UserCard key={user.id} user={user}/>);\n// After:\nif(!users)return <Skeleton/>;\nreturn users.map(user=><UserCard key={user.id} user={user}/>);","language":"typescript"},{"number":4,"title":"Catch errors in pre-commit","description":"Run TypeScript and ESLint before every commit to surface similar issues early.","code":"npx tsc --noEmit && npx eslint src/ --ext .ts,.tsx","language":"bash"}]'::jsonb,
NULL,NULL,840,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'load-test-script-generator','Load Test Script Generator','Generate k6 or Artillery load test scripts from API descriptions','Describe your API endpoints and target scenarios, get a runnable k6 script with ramp-up stages and p95 thresholds, then analyse results in Grafana or k6 Cloud.','developer-tools',NULL,
ARRAY['k6','load-testing','performance'],'intermediate',99900,900,false,
'[{"number":1,"title":"Describe your API","description":"Provide endpoint details and the ramp-up and sustained load scenarios.","code":"const script=await runSkill(loadTestScriptGenerator,{\n  api:{baseUrl:\"https://api.example.com\",endpoints:[{method:\"POST\",path:\"/api/skills/run\",body:{skillId:\"sql-query-builder\"}}]},\n  tool:\"k6\",\n  scenarios:{rampUp:\"0->100 users over 1min\",sustained:\"100 users for 5min\"}\n});","language":"typescript"},{"number":2,"title":"Generated k6 script","description":"The skill returns a complete k6 script with stages and p95 and error-rate thresholds.","code":"import http from \"k6/http\";\nimport{check,sleep}from \"k6\";\nexport const options={\n  stages:[\n    {duration:\"1m\",target:100},\n    {duration:\"5m\",target:100},\n    {duration:\"30s\",target:0}\n  ],\n  thresholds:{\"http_req_duration\":[\"p(95)<500\"],\"http_req_failed\":[\"rate<0.01\"]}\n};","language":"typescript"},{"number":3,"title":"Run the test","description":"Execute locally or stream results to k6 Cloud.","code":"k6 run script.js\n# With cloud output:\nk6 run --out cloud script.js","language":"bash"},{"number":4,"title":"Analyse results","description":"Check the three key metrics to confirm your API meets the SLA.","code":"# Key metrics:\n# http_req_duration p(95) < 500ms\n# http_req_failed rate < 1%\n# Check Grafana dashboard or k6 cloud for per-endpoint flamegraph","language":"bash"}]'::jsonb,
NULL,NULL,580,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'env-var-validator','Env Var Validator','Validate and type-check all environment variables at startup with Zod','Use Zod to parse process.env at boot, surface missing or malformed variables immediately, generate a typed env object, and add a CI check that fails fast on misconfiguration.','developer-tools',NULL,
ARRAY['zod','env','typescript'],'beginner',0,0,true,
'[{"number":1,"title":"Define the schema","description":"Declare every required and optional env var with its expected type and constraints.","code":"import{z}from\"zod\";\nconst envSchema=z.object({\n  DATABASE_URL:z.string().url(),\n  PORT:z.coerce.number().min(1024).max(65535).default(3000),\n  NODE_ENV:z.enum([\"development\",\"test\",\"production\"]),\n  STRIPE_SECRET_KEY:z.string().startsWith(\"sk_\"),\n  RESEND_API_KEY:z.string().optional()\n});","language":"typescript"},{"number":2,"title":"Parse at startup","description":"Call parse once at module load time so the process crashes loudly before serving any requests.","code":"export const env=envSchema.parse(process.env);\n// TypeScript now knows env.PORT is number, env.DATABASE_URL is string, etc.","language":"typescript"},{"number":3,"title":"Surface friendly errors","description":"Catch Zod errors and print a table of every missing or invalid variable before exiting.","code":"const result=envSchema.safeParse(process.env);\nif(!result.success){\n  console.error(\"Invalid environment variables:\");\n  result.error.issues.forEach(i=>console.error(` ${i.path.join(\".\")} — ${i.message}`));\n  process.exit(1);\n}","language":"typescript"},{"number":4,"title":"CI check for .env.example drift","description":"Add a script that parses .env.example through the schema to catch missing keys before deploy.","code":"// scripts/check-env.ts\nimport\"dotenv/config\";\nimport{envSchema}from\"../src/env\";\nconst result=envSchema.safeParse(process.env);\nif(!result.success){console.error(result.error.format());process.exit(1);}\nconsole.log(\"Env OK:\",Object.keys(result.data).length,\"vars validated\");","language":"typescript"}]'::jsonb,
NULL,NULL,690,0,0,true,true,false,NULL,true);

INSERT INTO skills (slug,title,tagline,description,category,subcategory,tags,difficulty,price_inr,price_usd,is_free,steps,video_url,video_thumbnail,trending_score,view_count,purchase_count,is_trending,is_new,is_featured,pack_id,published) VALUES (
'code-refactorer','Code Refactorer','Refactor code for readability, performance and maintainability','Submit messy code with refactoring goals, get a clean diff with named constants, extracted types, and removed duplication — then verify your tests still pass.','developer-tools',NULL,
ARRAY['refactoring','clean-code','typescript'],'intermediate',99900,900,false,
'[{"number":1,"title":"Submit code for review","description":"Pass the raw code and the refactoring goals to the skill.","code":"const result=await runSkill(codeRefactorer,{\n  code:uglyCode,\n  goals:[\"readability\",\"performance\",\"remove-duplication\"],\n  language:\"typescript\"\n});","language":"typescript"},{"number":2,"title":"Before and after diff","description":"The skill highlights the exact changes with named constants replacing magic numbers.","code":"// Before: nested conditionals, magic numbers\nfunction calc(x:number,t:number){if(t===1)return x*0.18;else if(t===2)return x*0.12;return x*0.05;}\n// After: named constants, clear intent\nconst GST_RATES={standard:0.18,reduced:0.12,exempt:0.05} as const;\ntype GSTCategory=keyof typeof GST_RATES;\nfunction calculateGST(amount:number,category:GSTCategory):number{return amount*GST_RATES[category];}","language":"typescript"},{"number":3,"title":"Apply changes","description":"Write the refactored code back to the original file path.","code":"import{writeFileSync}from\"fs\";\nwriteFileSync(filePath,result.data.refactoredCode,\"utf8\");","language":"typescript"},{"number":4,"title":"Verify tests pass","description":"Run the full test suite to confirm the refactor did not change behaviour.","code":"npm test -- --coverage 2>&1 | tail -20","language":"bash"}]'::jsonb,
NULL,NULL,720,0,0,true,true,false,NULL,true);
